/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Arn = string;
/**
 * The name of the Amazon Lookout for Vision project
 */
export type ProjectName = string;

/**
 * The AWS::LookoutVision::Project type creates an Amazon Lookout for Vision project. A project is a grouping of the resources needed to create and manage a Lookout for Vision model.
 */
export interface AwsLookoutvisionProject {
  Arn?: Arn;
  ProjectName: ProjectName;
}
