/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::SSM::Document resource is an SSM document in AWS Systems Manager that defines the actions that Systems Manager performs, which can be used to set up and run commands on your instances.
 */
export interface AwsSsmDocument {
  /**
   * The content for the Systems Manager document in JSON, YAML or String format.
   */
  Content:
    | {
        [k: string]: unknown;
      }
    | string;
  /**
   * A list of key and value pairs that describe attachments to a version of a document.
   *
   * @minItems 0
   * @maxItems 20
   */
  Attachments?:
    | []
    | [AttachmentsSource]
    | [AttachmentsSource, AttachmentsSource]
    | [AttachmentsSource, AttachmentsSource, AttachmentsSource]
    | [AttachmentsSource, AttachmentsSource, AttachmentsSource, AttachmentsSource]
    | [AttachmentsSource, AttachmentsSource, AttachmentsSource, AttachmentsSource, AttachmentsSource]
    | [AttachmentsSource, AttachmentsSource, AttachmentsSource, AttachmentsSource, AttachmentsSource, AttachmentsSource]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ]
    | [
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource,
        AttachmentsSource
      ];
  /**
   * A name for the Systems Manager document.
   */
  Name?: string;
  /**
   * An optional field specifying the version of the artifact you are creating with the document. This value is unique across all versions of a document, and cannot be changed.
   */
  VersionName?: string;
  /**
   * The type of document to create.
   */
  DocumentType?:
    | "ApplicationConfiguration"
    | "ApplicationConfigurationSchema"
    | "Automation"
    | "Automation.ChangeTemplate"
    | "ChangeCalendar"
    | "CloudFormation"
    | "Command"
    | "DeploymentStrategy"
    | "Package"
    | "Policy"
    | "ProblemAnalysis"
    | "ProblemAnalysisTemplate"
    | "Session";
  /**
   * Specify the document format for the request. The document format can be either JSON or YAML. JSON is the default format.
   */
  DocumentFormat?: "YAML" | "JSON" | "TEXT";
  /**
   * Specify a target type to define the kinds of resources the document can run on.
   */
  TargetType?: string;
  /**
   * Optional metadata that you assign to a resource. Tags enable you to categorize a resource in different ways, such as by purpose, owner, or environment.
   *
   * @maxItems 1000
   */
  Tags?: Tag[];
  /**
   * A list of SSM documents required by a document. For example, an ApplicationConfiguration document requires an ApplicationConfigurationSchema document.
   *
   * @minItems 1
   */
  Requires?: [DocumentRequires, ...DocumentRequires[]];
  /**
   * Update method - when set to 'Replace', the update will replace the existing document; when set to 'NewVersion', the update will create a new version.
   */
  UpdateMethod?: "Replace" | "NewVersion";
}
export interface AttachmentsSource {
  /**
   * The key of a key-value pair that identifies the location of an attachment to a document.
   */
  Key?: "SourceUrl" | "S3FileUrl" | "AttachmentReference";
  /**
   * The value of a key-value pair that identifies the location of an attachment to a document. The format for Value depends on the type of key you specify.
   *
   * @minItems 1
   * @maxItems 1
   */
  Values?: [string];
  /**
   * The name of the document attachment file.
   */
  Name?: string;
}
export interface Tag {
  /**
   * The name of the tag.
   */
  Key?: string;
  /**
   * The value of the tag.
   */
  Value?: string;
}
export interface DocumentRequires {
  /**
   * The name of the required SSM document. The name can be an Amazon Resource Name (ARN).
   */
  Name?: string;
  /**
   * The document version required by the current document.
   */
  Version?: string;
}
