/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SSM::MaintenanceWindow
 */
export interface AwsSsmMaintenancewindow {
  StartDate?: string;
  Description?: string;
  AllowUnassociatedTargets: boolean;
  Cutoff: number;
  Schedule: string;
  Duration: number;
  ScheduleOffset?: number;
  Id?: string;
  EndDate?: string;
  Tags?: Tag[];
  Name: string;
  ScheduleTimezone?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
