/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SSM::ResourcePolicy
 */
export interface AwsSsmResourcepolicy {
  /**
   * Arn of OpsItemGroup etc.
   */
  ResourceArn: string;
  /**
   * Actual policy statement.
   */
  Policy:
    | {
        [k: string]: unknown;
      }
    | string;
  /**
   * An unique identifier within the policies of a resource.
   */
  PolicyId?: string;
  /**
   * A snapshot identifier for the policy over time.
   */
  PolicyHash?: string;
}
