/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource schema for AWS::ImageBuilder::ImagePipeline
 */
export type AwsImagebuilderImagepipeline = {
  /**
   * The Amazon Resource Name (ARN) of the image pipeline.
   */
  Arn?: string;
  /**
   * The name of the image pipeline.
   */
  Name?: string;
  /**
   * The description of the image pipeline.
   */
  Description?: string;
  ImageTestsConfiguration?: ImageTestsConfiguration;
  /**
   * The status of the image pipeline.
   */
  Status?: "DISABLED" | "ENABLED";
  Schedule?: Schedule;
  /**
   * The Amazon Resource Name (ARN) of the image recipe that defines how images are configured, tested, and assessed.
   */
  ImageRecipeArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the container recipe that defines how images are configured and tested.
   */
  ContainerRecipeArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the distribution configuration associated with this image pipeline.
   */
  DistributionConfigurationArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the infrastructure configuration associated with this image pipeline.
   */
  InfrastructureConfigurationArn?: string;
  /**
   * Collects additional information about the image being created, including the operating system (OS) version and package list.
   */
  EnhancedImageMetadataEnabled?: boolean;
  ImageScanningConfiguration?: ImageScanningConfiguration;
  /**
   * The tags of this image pipeline.
   */
  Tags?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".{1,}".
     */
    [k: string]: string;
  };
} & {
  [k: string]: unknown;
};

/**
 * The image tests configuration of the image pipeline.
 */
export interface ImageTestsConfiguration {
  /**
   * Defines if tests should be executed when building this image.
   */
  ImageTestsEnabled?: boolean;
  /**
   * The maximum time in minutes that tests are permitted to run.
   */
  TimeoutMinutes?: number;
}
/**
 * The schedule of the image pipeline.
 */
export interface Schedule {
  /**
   * The expression determines how often EC2 Image Builder evaluates your pipelineExecutionStartCondition.
   */
  ScheduleExpression?: string;
  /**
   * The condition configures when the pipeline should trigger a new image build.
   */
  PipelineExecutionStartCondition?: "EXPRESSION_MATCH_ONLY" | "EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE";
}
/**
 * Contains settings for vulnerability scans.
 */
export interface ImageScanningConfiguration {
  EcrConfiguration?: EcrConfiguration;
  /**
   * This sets whether Image Builder keeps a snapshot of the vulnerability scans that Amazon Inspector runs against the build instance when you create a new image.
   */
  ImageScanningEnabled?: boolean;
}
/**
 * Contains ECR settings for vulnerability scans.
 */
export interface EcrConfiguration {
  /**
   * Tags for Image Builder to apply the output container image that is scanned. Tags can help you identify and manage your scanned images.
   */
  ContainerTags?: string[];
  /**
   * The name of the container repository that Amazon Inspector scans to identify findings for your container images. The name includes the path for the repository location. If you don’t provide this information, Image Builder creates a repository in your account named image-builder-image-scanning-repository to use for vulnerability scans for your output container images.
   */
  RepositoryName?: string;
}
