/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PackageOwnerAccount = string;
export type NodePackageId = string;
export type NodePackageArn = string;
export type NodePackageVersion = string;
export type NodePackagePatchVersion = string;
export type NodePackageName = string;
export type PackageVersionStatus = "REGISTER_PENDING" | "REGISTER_COMPLETED" | "FAILED" | "DELETING";
export type PackageVersionStatusDescription = string;
export type TimeStamp = number;

/**
 * Schema for PackageVersion Resource Type
 */
export interface AwsPanoramaPackageversion {
  OwnerAccount?: PackageOwnerAccount;
  PackageId: NodePackageId;
  PackageArn?: NodePackageArn;
  PackageVersion: NodePackageVersion;
  PatchVersion: NodePackagePatchVersion;
  MarkLatest?: boolean;
  IsLatestPatch?: boolean;
  PackageName?: NodePackageName;
  Status?: PackageVersionStatus;
  StatusDescription?: PackageVersionStatusDescription;
  RegisteredTime?: TimeStamp;
  UpdatedLatestPatchVersion?: NodePackagePatchVersion;
}
