/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::GameLift::Script
 */
export interface AwsGameliftScript {
  Id?: string;
  Arn?: string;
  StorageLocation: S3Location;
  Version?: string;
  Tags?: Tag[];
  Name?: string;
}
export interface S3Location {
  ObjectVersion?: string;
  Bucket: string;
  Key: string;
  RoleArn: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
