/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource type definition for AWS::IVSChat::Room.
 */
export interface AwsIvschatRoom {
  /**
   * Room ARN is automatically generated on creation and assigned as the unique identifier.
   */
  Arn?: string;
  /**
   * The system-generated ID of the room.
   */
  Id?: string;
  /**
   * The name of the room. The value does not need to be unique.
   */
  Name?: string;
  /**
   * Array of logging configuration identifiers attached to the room.
   *
   * @minItems 0
   * @maxItems 50
   */
  LoggingConfigurationIdentifiers?: string[];
  /**
   * The maximum number of characters in a single message.
   */
  MaximumMessageLength?: number;
  /**
   * The maximum number of messages per second that can be sent to the room.
   */
  MaximumMessageRatePerSecond?: number;
  MessageReviewHandler?: MessageReviewHandler;
  /**
   * An array of key-value pairs to apply to this resource.
   */
  Tags?: Tag[];
}
/**
 * Configuration information for optional review of messages.
 */
export interface MessageReviewHandler {
  /**
   * Specifies the fallback behavior if the handler does not return a valid response, encounters an error, or times out.
   */
  FallbackResult?: "ALLOW" | "DENY";
  /**
   * Identifier of the message review handler.
   */
  Uri?: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
