/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Pinpoint::EmailChannel
 */
export interface AwsPinpointEmailchannel {
  Id?: string;
  ConfigurationSet?: string;
  FromAddress: string;
  Enabled?: boolean;
  ApplicationId: string;
  Identity: string;
  RoleArn?: string;
}
