/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Pinpoint::PushTemplate
 */
export interface AwsPinpointPushtemplate {
  GCM?: AndroidPushNotificationTemplate;
  Baidu?: AndroidPushNotificationTemplate;
  TemplateName: string;
  ADM?: AndroidPushNotificationTemplate;
  APNS?: APNSPushNotificationTemplate;
  TemplateDescription?: string;
  DefaultSubstitutions?: string;
  Id?: string;
  Arn?: string;
  Default?: DefaultPushNotificationTemplate;
  Tags?: {
    [k: string]: unknown;
  };
}
export interface AndroidPushNotificationTemplate {
  Action?: string;
  ImageUrl?: string;
  SmallImageIconUrl?: string;
  Title?: string;
  ImageIconUrl?: string;
  Sound?: string;
  Body?: string;
  Url?: string;
}
export interface APNSPushNotificationTemplate {
  Action?: string;
  MediaUrl?: string;
  Title?: string;
  Sound?: string;
  Body?: string;
  Url?: string;
}
export interface DefaultPushNotificationTemplate {
  Title?: string;
  Action?: string;
  Sound?: string;
  Body?: string;
  Url?: string;
}
