/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::DocDBElastic::Cluster Amazon DocumentDB (with MongoDB compatibility) Elastic Scale resource describes a Cluster
 */
export interface AwsDocdbelasticCluster {
  ClusterName: string;
  ClusterArn?: string;
  ClusterEndpoint?: string;
  AdminUserName: string;
  AdminUserPassword?: string;
  ShardCapacity: number;
  ShardCount: number;
  VpcSecurityGroupIds?: string[];
  SubnetIds?: string[];
  PreferredMaintenanceWindow?: string;
  KmsKeyId?: string;
  /**
   * @minItems 0
   * @maxItems 50
   */
  Tags?: Tag[];
  AuthType: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
