/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Backup::BackupPlan
 */
export interface AwsBackupBackupplan {
  BackupPlan: BackupPlanResourceType;
  BackupPlanTags?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.{1,128}$".
     */
    [k: string]: string;
  };
  BackupPlanArn?: string;
  BackupPlanId?: string;
  VersionId?: string;
}
export interface BackupPlanResourceType {
  BackupPlanName: string;
  AdvancedBackupSettings?: AdvancedBackupSettingResourceType[];
  BackupPlanRule: BackupRuleResourceType[];
}
export interface AdvancedBackupSettingResourceType {
  BackupOptions: {
    [k: string]: unknown;
  };
  ResourceType: string;
}
export interface BackupRuleResourceType {
  RuleName: string;
  TargetBackupVault: string;
  StartWindowMinutes?: number;
  CompletionWindowMinutes?: number;
  ScheduleExpression?: string;
  RecoveryPointTags?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.{1,128}$".
     */
    [k: string]: string;
  };
  CopyActions?: CopyActionResourceType[];
  Lifecycle?: LifecycleResourceType;
  EnableContinuousBackup?: boolean;
}
export interface CopyActionResourceType {
  Lifecycle?: LifecycleResourceType;
  DestinationBackupVaultArn: string;
}
export interface LifecycleResourceType {
  MoveToColdStorageAfterDays?: number;
  DeleteAfterDays?: number;
}
