/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Destination's resource schema demonstrating some basic constructs and validation rules.
 */
export interface AwsIotwirelessDestination {
  /**
   * Unique name of destination
   */
  Name: string;
  /**
   * Destination expression
   */
  Expression: string;
  /**
   * Must be RuleName
   */
  ExpressionType: "RuleName" | "MqttTopic";
  /**
   * Destination description
   */
  Description?: string;
  /**
   * A list of key-value pairs that contain metadata for the destination.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * AWS role ARN that grants access
   */
  RoleArn: string;
  /**
   * Destination arn. Returned after successful create.
   */
  Arn?: string;
}
export interface Tag {
  Key?: string;
  Value?: string;
}
