/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FactoryPresetFreq = number;

/**
 * Device Profile's resource schema demonstrating some basic constructs and validation rules.
 */
export interface AwsIotwirelessDeviceprofile {
  /**
   * Name of service profile
   */
  Name?: string;
  LoRaWAN?: LoRaWANDeviceProfile;
  /**
   * A list of key-value pairs that contain metadata for the device profile.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * Service profile Arn. Returned after successful create.
   */
  Arn?: string;
  /**
   * Service profile Id. Returned after successful create.
   */
  Id?: string;
}
/**
 * LoRaWANDeviceProfile supports all LoRa specific attributes for service profile for CreateDeviceProfile operation
 */
export interface LoRaWANDeviceProfile {
  SupportsClassB?: boolean;
  ClassBTimeout?: number;
  PingSlotPeriod?: number;
  PingSlotDr?: number;
  PingSlotFreq?: number;
  SupportsClassC?: boolean;
  ClassCTimeout?: number;
  MacVersion?: string;
  RegParamsRevision?: string;
  RxDelay1?: number;
  RxDrOffset1?: number;
  RxFreq2?: number;
  RxDataRate2?: number;
  /**
   * @maxItems 20
   */
  FactoryPresetFreqsList?:
    | []
    | [FactoryPresetFreq]
    | [FactoryPresetFreq, FactoryPresetFreq]
    | [FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq]
    | [FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq]
    | [FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq]
    | [FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq, FactoryPresetFreq]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ]
    | [
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq,
        FactoryPresetFreq
      ];
  MaxEirp?: number;
  MaxDutyCycle?: number;
  SupportsJoin?: boolean;
  RfRegion?: string;
  Supports32BitFCnt?: boolean;
}
export interface Tag {
  Key?: string;
  Value?: string;
}
