/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Create and manage partner account
 */
export interface AwsIotwirelessPartneraccount {
  Sidewalk?: SidewalkAccountInfo;
  /**
   * The partner account ID to disassociate from the AWS account
   */
  PartnerAccountId?: string;
  /**
   * The partner type
   */
  PartnerType?: "Sidewalk";
  SidewalkResponse?: SidewalkAccountInfoWithFingerprint;
  /**
   * Whether the partner account is linked to the AWS account.
   */
  AccountLinked?: boolean;
  SidewalkUpdate?: SidewalkUpdateAccount;
  /**
   * The fingerprint of the Sidewalk application server private key.
   */
  Fingerprint?: string;
  /**
   * PartnerAccount arn. Returned after successful create.
   */
  Arn?: string;
  /**
   * A list of key-value pairs that contain metadata for the destination.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
}
/**
 * The Sidewalk account credentials.
 */
export interface SidewalkAccountInfo {
  AppServerPrivateKey: string;
}
/**
 * The Sidewalk account credentials.
 */
export interface SidewalkAccountInfoWithFingerprint {
  AmazonId?: string;
  Fingerprint?: string;
  Arn?: string;
}
/**
 * The Sidewalk account credentials.
 */
export interface SidewalkUpdateAccount {
  AppServerPrivateKey?: string;
}
export interface Tag {
  Key?: string;
  Value?: string;
}
