/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Set a version as default version for a hook in CloudFormation Registry.
 */
export type AwsCloudformationHookdefaultversion = {
  /**
   * The Amazon Resource Name (ARN) of the type version.
   */
  TypeVersionArn?: string;
  /**
   * The name of the type being registered.
   *
   * We recommend that type names adhere to the following pattern: company_or_organization::service::type.
   */
  TypeName?: string;
  /**
   * The Amazon Resource Name (ARN) of the type. This is used to uniquely identify a HookDefaultVersion
   */
  Arn?: string;
  /**
   * The ID of an existing version of the hook to set as the default.
   */
  VersionId?: string;
} & {
  [k: string]: unknown;
};
