/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Test and Publish a resource that has been registered in the CloudFormation Registry.
 */
export type AwsCloudformationPublictypeversion = {
  /**
   * The Amazon Resource Number (ARN) of the extension.
   */
  Arn?: string;
  /**
   * The Amazon Resource Number (ARN) of the extension with the versionId.
   */
  TypeVersionArn?: string;
  /**
   * The version number of a public third-party extension
   */
  PublicVersionNumber?: string;
  /**
   * The publisher id assigned by CloudFormation for publishing in this region.
   */
  PublisherId?: string;
  /**
   * The Amazon Resource Number (ARN) assigned to the public extension upon publication
   */
  PublicTypeArn?: string;
  /**
   * The name of the type being registered.
   *
   * We recommend that type names adhere to the following pattern: company_or_organization::service::type.
   */
  TypeName?: string;
  /**
   * A url to the S3 bucket where logs for the testType run will be available
   */
  LogDeliveryBucket?: string;
  /**
   * The kind of extension
   */
  Type?: "RESOURCE" | "MODULE" | "HOOK";
} & {
  [k: string]: unknown;
};
