/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::CUR::ReportDefinition resource creates a Cost & Usage Report with user-defined settings. You can use this resource to define settings like time granularity (hourly, daily, monthly), file format (Parquet, CSV), and S3 bucket for delivery of these reports.
 */
export interface AwsCurReportdefinition {
  /**
   * The name of the report that you want to create. The name must be unique, is case sensitive, and can't include spaces.
   */
  ReportName: string;
  /**
   * The granularity of the line items in the report.
   */
  TimeUnit: "HOURLY" | "DAILY" | "MONTHLY";
  /**
   * The format that AWS saves the report in.
   */
  Format: "textORcsv" | "Parquet";
  /**
   * The compression format that AWS uses for the report.
   */
  Compression: "ZIP" | "GZIP" | "Parquet";
  /**
   * A list of strings that indicate additional content that Amazon Web Services includes in the report, such as individual resource IDs.
   */
  AdditionalSchemaElements?: "RESOURCES"[];
  /**
   * The S3 bucket where AWS delivers the report.
   */
  S3Bucket: string;
  /**
   * The prefix that AWS adds to the report name when AWS delivers the report. Your prefix can't include spaces.
   */
  S3Prefix: string;
  /**
   * The region of the S3 bucket that AWS delivers the report into.
   */
  S3Region: string;
  /**
   * A list of manifests that you want Amazon Web Services to create for this report.
   */
  AdditionalArtifacts?: ("REDSHIFT" | "QUICKSIGHT" | "ATHENA")[];
  /**
   * Whether you want Amazon Web Services to update your reports after they have been finalized if Amazon Web Services detects charges related to previous months. These charges can include refunds, credits, or support fees.
   */
  RefreshClosedReports: boolean;
  /**
   * Whether you want Amazon Web Services to overwrite the previous version of each report or to deliver the report in addition to the previous versions.
   */
  ReportVersioning: "CREATE_NEW_REPORT" | "OVERWRITE_REPORT";
  /**
   * The Amazon resource name of the billing view. You can get this value by using the billing view service public APIs.
   */
  BillingViewArn?: string;
}
