/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AWS::SimSpaceWeaver::Simulation resource creates an AWS Simulation.
 */
export interface AwsSimspaceweaverSimulation {
  /**
   * The name of the simulation.
   */
  Name?: string;
  /**
   * Role ARN.
   */
  RoleArn?: string;
  SchemaS3Location?: S3Location;
  /**
   * Json object with all simulation details
   */
  DescribePayload?: string;
}
export interface S3Location {
  /**
   * The Schema S3 bucket name.
   */
  BucketName: string;
  /**
   * This is the schema S3 object key, which includes the full path of "folders" from the bucket root to the schema.
   */
  ObjectKey: string;
}
