/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ResourceStatus =
  | "CREATION_IN_PROGRESS"
  | "CREATION_SUCCESSFUL"
  | "CREATION_FAILED"
  | "UPDATE_IN_PROGRESS"
  | "UPDATE_SUCCESSFUL"
  | "UPDATE_FAILED"
  | "DELETED";
export type TemplateErrorType = "SOURCE_NOT_FOUND" | "DATA_SET_NOT_FOUND" | "INTERNAL_FAILURE" | "ACCESS_DENIED";

/**
 * Definition of the AWS::QuickSight::Template Resource Type.
 */
export interface AwsQuicksightTemplate {
  /**
   * <p>The Amazon Resource Name (ARN) of the template.</p>
   */
  Arn?: string;
  AwsAccountId: string;
  /**
   * <p>Time when this was created.</p>
   */
  CreatedTime?: string;
  /**
   * <p>Time when this was last updated.</p>
   */
  LastUpdatedTime?: string;
  /**
   * <p>A display name for the template.</p>
   */
  Name?: string;
  /**
   * <p>A list of resource permissions to be set on the template. </p>
   *
   * @minItems 1
   * @maxItems 64
   */
  Permissions?: [ResourcePermission, ...ResourcePermission[]];
  SourceEntity: TemplateSourceEntity;
  /**
   * <p>Contains a map of the key-value pairs for the resource tag or tags assigned to the resource.</p>
   *
   * @minItems 1
   * @maxItems 200
   */
  Tags?: [Tag, ...Tag[]];
  TemplateId: string;
  Version?: TemplateVersion;
  /**
   * <p>A description of the current template version being created. This API operation creates the
   * 			first version of the template. Every time <code>UpdateTemplate</code> is called, a new
   * 			version is created. Each version of the template maintains a description of the version
   * 			in the <code>VersionDescription</code> field.</p>
   */
  VersionDescription?: string;
}
/**
 * <p>Permission for the resource.</p>
 */
export interface ResourcePermission {
  /**
   * <p>The IAM action to grant or revoke permissions on.</p>
   *
   * @minItems 1
   * @maxItems 16
   */
  Actions:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * <p>The Amazon Resource Name (ARN) of the principal. This can be one of the
   *             following:</p>
   *         <ul>
   *             <li>
   *                 <p>The ARN of an Amazon QuickSight user or group associated with a data source or dataset. (This is common.)</p>
   *             </li>
   *             <li>
   *                 <p>The ARN of an Amazon QuickSight user, group, or namespace associated with an analysis, dashboard, template, or theme. (This is common.)</p>
   *             </li>
   *             <li>
   *                 <p>The ARN of an AWS account root: This is an IAM ARN rather than a QuickSight
   *                     ARN. Use this option only to share resources (templates) across AWS accounts.
   *                     (This is less common.) </p>
   *             </li>
   *          </ul>
   */
  Principal: string;
}
/**
 * <p>The source entity of the template.</p>
 */
export interface TemplateSourceEntity {
  SourceAnalysis?: TemplateSourceAnalysis;
  SourceTemplate?: TemplateSourceTemplate;
}
/**
 * <p>The source analysis of the template.</p>
 */
export interface TemplateSourceAnalysis {
  /**
   * <p>A structure containing information about the dataset references used as placeholders
   *             in the template.</p>
   *
   * @minItems 1
   */
  DataSetReferences: [DataSetReference, ...DataSetReference[]];
  /**
   * <p>The Amazon Resource Name (ARN) of the resource.</p>
   */
  Arn: string;
}
/**
 * <p>Dataset reference.</p>
 */
export interface DataSetReference {
  /**
   * <p>Dataset Amazon Resource Name (ARN).</p>
   */
  DataSetArn: string;
  /**
   * <p>Dataset placeholder.</p>
   */
  DataSetPlaceholder: string;
}
/**
 * <p>The source template of the template.</p>
 */
export interface TemplateSourceTemplate {
  /**
   * <p>The Amazon Resource Name (ARN) of the resource.</p>
   */
  Arn: string;
}
/**
 * <p>The key or keys of the key-value pairs for the resource tag or tags assigned to the
 *             resource.</p>
 */
export interface Tag {
  /**
   * <p>Tag value.</p>
   */
  Value: string;
  /**
   * <p>Tag key.</p>
   */
  Key: string;
}
/**
 * <p>A version of a template.</p>
 */
export interface TemplateVersion {
  Status?: ResourceStatus;
  /**
   * <p>Errors associated with this template version.</p>
   *
   * @minItems 1
   */
  Errors?: [TemplateError, ...TemplateError[]];
  /**
   * <p>The time that this template version was created.</p>
   */
  CreatedTime?: string;
  /**
   * <p>The description of the template.</p>
   */
  Description?: string;
  /**
   * <p>The ARN of the theme associated with this version of the template.</p>
   */
  ThemeArn?: string;
  /**
   * <p>Schema of the dataset identified by the placeholder. Any dashboard created from this
   *             template should be bound to new datasets matching the same schema described through this
   *             API operation.</p>
   *
   * @minItems 0
   * @maxItems 30
   */
  DataSetConfigurations?: DataSetConfiguration[];
  /**
   * <p>The Amazon Resource Name (ARN) of an analysis or template that was used to create this
   *             template.</p>
   */
  SourceEntityArn?: string;
  /**
   * <p>The version number of the template version.</p>
   */
  VersionNumber?: number;
  /**
   * <p>A list of the associated sheets with the unique identifier and name of each sheet.</p>
   *
   * @minItems 0
   * @maxItems 20
   */
  Sheets?:
    | []
    | [Sheet]
    | [Sheet, Sheet]
    | [Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet, Sheet]
    | [
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet
      ]
    | [
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet
      ]
    | [
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet
      ]
    | [
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet,
        Sheet
      ];
}
/**
 * <p>List of errors that occurred when the template version creation failed.</p>
 */
export interface TemplateError {
  Type?: TemplateErrorType;
  /**
   * <p>Description of the error type.</p>
   */
  Message?: string;
}
/**
 * <p>Dataset configuration.</p>
 */
export interface DataSetConfiguration {
  /**
   * <p>Placeholder.</p>
   */
  Placeholder?: string;
  DataSetSchema?: DataSetSchema;
  /**
   * <p>A structure containing the list of column group schemas.</p>
   *
   * @minItems 0
   * @maxItems 500
   */
  ColumnGroupSchemaList?: ColumnGroupSchema[];
}
/**
 * <p>Dataset schema.</p>
 */
export interface DataSetSchema {
  /**
   * <p>A structure containing the list of column schemas.</p>
   *
   * @minItems 0
   * @maxItems 500
   */
  ColumnSchemaList?: ColumnSchema[];
}
/**
 * <p>The column schema.</p>
 */
export interface ColumnSchema {
  /**
   * <p>The data type of the column schema.</p>
   */
  DataType?: string;
  /**
   * <p>The geographic role of the column schema.</p>
   */
  GeographicRole?: string;
  /**
   * <p>The name of the column schema.</p>
   */
  Name?: string;
}
/**
 * <p>The column group schema.</p>
 */
export interface ColumnGroupSchema {
  /**
   * <p>A structure containing the list of schemas for column group columns.</p>
   *
   * @minItems 0
   * @maxItems 500
   */
  ColumnGroupColumnSchemaList?: ColumnGroupColumnSchema[];
  /**
   * <p>The name of the column group schema.</p>
   */
  Name?: string;
}
/**
 * <p>A structure describing the name, data type, and geographic role of the columns.</p>
 */
export interface ColumnGroupColumnSchema {
  /**
   * <p>The name of the column group's column schema.</p>
   */
  Name?: string;
}
/**
 * <p>A <i>sheet</i>, which is an object that contains a set of visuals that
 *             are viewed together on one page in the Amazon QuickSight console. Every analysis and dashboard
 *             contains at least one sheet. Each sheet contains at least one visualization widget, for
 *             example a chart, pivot table, or narrative insight. Sheets can be associated with other
 *             components, such as controls, filters, and so on.</p>
 */
export interface Sheet {
  /**
   * <p>The unique identifier associated with a sheet.</p>
   */
  SheetId?: string;
  /**
   * <p>The name of a sheet. This name is displayed on the sheet's tab in the QuickSight
   *             console.</p>
   */
  Name?: string;
}
