/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Creates an authorizer.
 */
export interface AwsIotAuthorizer {
  AuthorizerFunctionArn: string;
  Arn?: string;
  AuthorizerName?: string;
  SigningDisabled?: boolean;
  Status?: "ACTIVE" | "INACTIVE";
  TokenKeyName?: string;
  TokenSigningPublicKeys?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9:_-]+".
     */
    [k: string]: string;
  };
  EnableCachingForHttp?: boolean;
  Tags?: Tag[];
}
export interface Tag {
  Key: string;
  Value: string;
}
