/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Logging Options enable you to configure your IoT V2 logging role and default logging level so that you can monitor progress events logs as it passes from your devices through Iot core service.
 */
export interface AwsIotLogging {
  /**
   * Your 12-digit account ID (used as the primary identifier for the CloudFormation resource).
   */
  AccountId: string;
  /**
   * The ARN of the role that allows IoT to write to Cloudwatch logs.
   */
  RoleArn: string;
  /**
   * The log level to use. Valid values are: ERROR, WARN, INFO, DEBUG, or DISABLED.
   */
  DefaultLogLevel: "ERROR" | "WARN" | "INFO" | "DEBUG" | "DISABLED";
}
