/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Creates a fleet provisioning template.
 */
export interface AwsIotProvisioningtemplate {
  TemplateArn?: string;
  TemplateName?: string;
  Description?: string;
  Enabled?: boolean;
  ProvisioningRoleArn: string;
  TemplateBody: string;
  TemplateType?: "FLEET_PROVISIONING" | "JITP";
  PreProvisioningHook?: ProvisioningHook;
  Tags?: Tag[];
}
export interface ProvisioningHook {
  TargetArn?: string;
  PayloadVersion?: string;
  [k: string]: unknown;
}
export interface Tag {
  Key: string;
  Value: string;
}
