/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::CapacityReservationFleet
 */
export interface AwsEc2Capacityreservationfleet {
  AllocationStrategy?: string;
  TagSpecifications?: TagSpecification[];
  /**
   * @maxItems 50
   */
  InstanceTypeSpecifications?: InstanceTypeSpecification[];
  TotalTargetCapacity?: number;
  EndDate?: string;
  InstanceMatchCriteria?: "open";
  CapacityReservationFleetId?: string;
  Tenancy?: "default";
  RemoveEndDate?: boolean;
  NoRemoveEndDate?: boolean;
}
export interface TagSpecification {
  ResourceType?: string;
  Tags?: Tag[];
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface InstanceTypeSpecification {
  InstanceType?: string;
  InstancePlatform?: string;
  Weight?: number;
  AvailabilityZone?: string;
  AvailabilityZoneId?: string;
  EbsOptimized?: boolean;
  Priority?: number;
}
