/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::CustomerGateway
 */
export interface AwsEc2Customergateway {
  /**
   * CustomerGateway ID generated after customer gateway is created. Each customer gateway has a unique ID.
   */
  CustomerGatewayId?: string;
  /**
   * For devices that support BGP, the customer gateway's BGP ASN.
   */
  BgpAsn: number;
  /**
   * The internet-routable IP address for the customer gateway's outside interface. The address must be static.
   */
  IpAddress: string;
  /**
   * One or more tags for the customer gateway.
   */
  Tags?: Tag[];
  /**
   * The type of VPN connection that this customer gateway supports.
   */
  Type: string;
  /**
   * A name for the customer gateway device.
   */
  DeviceName?: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
