/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::Host
 */
export interface AwsEc2Host {
  /**
   * Id of the host created.
   */
  HostId?: string;
  /**
   * Indicates whether the host accepts any untargeted instance launches that match its instance type configuration, or if it only accepts Host tenancy instance launches that specify its unique host ID.
   */
  AutoPlacement?: string;
  /**
   * The Availability Zone in which to allocate the Dedicated Host.
   */
  AvailabilityZone: string;
  /**
   * Indicates whether to enable or disable host recovery for the Dedicated Host. Host recovery is disabled by default.
   */
  HostRecovery?: string;
  /**
   * Specifies the instance type to be supported by the Dedicated Hosts. If you specify an instance type, the Dedicated Hosts support instances of the specified instance type only.
   */
  InstanceType?: string;
  /**
   * Specifies the instance family to be supported by the Dedicated Hosts. If you specify an instance family, the Dedicated Hosts support multiple instance types within that instance family.
   */
  InstanceFamily?: string;
  /**
   * The Amazon Resource Name (ARN) of the Amazon Web Services Outpost on which to allocate the Dedicated Host.
   */
  OutpostArn?: string;
}
