/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::InternetGateway
 */
export interface AwsEc2Internetgateway {
  /**
   * ID of internet gateway.
   */
  InternetGatewayId?: string;
  /**
   * Any tags to assign to the internet gateway.
   */
  Tags?: Tag[];
}
export interface Tag {
  Key: string;
  Value: string;
}
