/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Schema of AWS::EC2::IPAMScope Type
 */
export interface AwsEc2Ipamscope {
  /**
   * Id of the IPAM scope.
   */
  IpamScopeId?: string;
  /**
   * The Amazon Resource Name (ARN) of the IPAM scope.
   */
  Arn?: string;
  /**
   * The Id of the IPAM this scope is a part of.
   */
  IpamId: string;
  /**
   * The Amazon Resource Name (ARN) of the IPAM this scope is a part of.
   */
  IpamArn?: string;
  /**
   * Determines whether this scope contains publicly routable space or space for a private network
   */
  IpamScopeType?: "public" | "private";
  /**
   * Is this one of the default scopes created with the IPAM.
   */
  IsDefault?: boolean;
  Description?: string;
  /**
   * The number of pools that currently exist in this scope.
   */
  PoolCount?: number;
  /**
   * An array of key-value pairs to apply to this resource.
   */
  Tags?: Tag[];
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
