/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a single IPv4 or IPv6 CIDR
 */
export type Cidr = string;

/**
 * Resource Schema of AWS::EC2::IPAMAllocation Type
 */
export interface AwsEc2Ipamallocation {
  /**
   * Id of the allocation.
   */
  IpamPoolAllocationId?: string;
  /**
   * Id of the IPAM Pool.
   */
  IpamPoolId: string;
  Cidr?: Cidr;
  /**
   * The desired netmask length of the allocation. If set, IPAM will choose a block of free space with this size and return the CIDR representing it.
   */
  NetmaskLength?: number;
  Description?: string;
}
