/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Schema of AWS::EC2::IPAMPoolCidr Type
 */
export interface AwsEc2Ipampoolcidr {
  /**
   * Id of the IPAM Pool Cidr.
   */
  IpamPoolCidrId?: string;
  /**
   * Id of the IPAM Pool.
   */
  IpamPoolId: string;
  /**
   * Represents a single IPv4 or IPv6 CIDR
   */
  Cidr?: string;
  /**
   * The desired netmask length of the provision. If set, IPAM will choose a block of free space with this size and return the CIDR representing it.
   */
  NetmaskLength?: number;
  /**
   * Provisioned state of the cidr.
   */
  State?: string;
}
