/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The tags for the local gateway route table.
 */
export type Tags = Tag[];

/**
 * Describes a route table for a local gateway.
 */
export interface AwsEc2Localgatewayroutetable {
  /**
   * The ID of the local gateway route table.
   */
  LocalGatewayRouteTableId?: string;
  /**
   * The ARN of the local gateway route table.
   */
  LocalGatewayRouteTableArn?: string;
  /**
   * The ID of the local gateway.
   */
  LocalGatewayId: string;
  /**
   * The ARN of the outpost.
   */
  OutpostArn?: string;
  /**
   * The owner of the local gateway route table.
   */
  OwnerId?: string;
  /**
   * The state of the local gateway route table.
   */
  State?: string;
  /**
   * The mode of the local gateway route table.
   */
  Mode?: string;
  Tags?: Tags;
}
export interface Tag {
  Key?: string;
  Value?: string;
}
