/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::SecurityGroupIngress
 */
export interface AwsEc2Securitygroupingress {
  Id?: string;
  CidrIp?: string;
  CidrIpv6?: string;
  Description?: string;
  FromPort?: number;
  GroupId?: string;
  GroupName?: string;
  IpProtocol: string;
  SourcePrefixListId?: string;
  SourceSecurityGroupId?: string;
  SourceSecurityGroupName?: string;
  SourceSecurityGroupOwnerId?: string;
  ToPort?: number;
}
