/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::TransitGatewayAttachment
 */
export interface AwsEc2Transitgatewayattachment {
  Id?: string;
  TransitGatewayId: string;
  VpcId: string;
  SubnetIds: string[];
  Tags?: Tag[];
  /**
   * The options for the transit gateway vpc attachment.
   */
  Options?: {
    /**
     * Indicates whether to enable DNS Support for Vpc Attachment. Valid Values: enable | disable
     */
    DnsSupport?: string;
    /**
     * Indicates whether to enable Ipv6 Support for Vpc Attachment. Valid Values: enable | disable
     */
    Ipv6Support?: string;
    /**
     * Indicates whether to enable Ipv6 Support for Vpc Attachment. Valid Values: enable | disable
     */
    ApplianceModeSupport?: string;
  };
}
export interface Tag {
  Key: string;
  Value: string;
}
