/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::VPNConnectionRoute
 */
export interface AwsEc2Vpnconnectionroute {
  /**
   * The CIDR block associated with the local subnet of the customer network.
   */
  DestinationCidrBlock: string;
  /**
   * The ID of the VPN connection.
   */
  VpnConnectionId: string;
}
