/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for EC2 VPN Gateway
 */
export interface AwsEc2Vpngateway {
  /**
   * VPN Gateway ID generated by service
   */
  VPNGatewayId?: string;
  /**
   * The private Autonomous System Number (ASN) for the Amazon side of a BGP session.
   */
  AmazonSideAsn?: number;
  /**
   * Any tags assigned to the virtual private gateway.
   */
  Tags?: Tag[];
  /**
   * The type of VPN connection the virtual private gateway supports.
   */
  Type: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
