/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource schema for AWS::DataSync::LocationS3
 */
export interface AwsDatasyncLocations3 {
  S3Config: S3Config;
  /**
   * The Amazon Resource Name (ARN) of the Amazon S3 bucket.
   */
  S3BucketArn?: string;
  /**
   * A subdirectory in the Amazon S3 bucket. This subdirectory in Amazon S3 is used to read data from the S3 source location or write data to the S3 destination.
   */
  Subdirectory?: string;
  /**
   * The Amazon S3 storage class you want to store your files in when this location is used as a task destination.
   */
  S3StorageClass?:
    | "STANDARD"
    | "STANDARD_IA"
    | "ONEZONE_IA"
    | "INTELLIGENT_TIERING"
    | "GLACIER"
    | "GLACIER_INSTANT_RETRIEVAL"
    | "DEEP_ARCHIVE";
  /**
   * An array of key-value pairs to apply to this resource.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
  /**
   * The Amazon Resource Name (ARN) of the Amazon S3 bucket location.
   */
  LocationArn?: string;
  /**
   * The URL of the S3 location that was described.
   */
  LocationUri?: string;
}
/**
 * The Amazon Resource Name (ARN) of the AWS IAM role that is used to access an Amazon S3 bucket.
 */
export interface S3Config {
  /**
   * The ARN of the IAM role of the Amazon S3 bucket.
   */
  BucketAccessRoleArn: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key for an AWS resource tag.
   */
  Key: string;
  /**
   * The value for an AWS resource tag.
   */
  Value: string;
}
