/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::CloudFront::CachePolicy
 */
export interface AwsCloudfrontCachepolicy {
  CachePolicyConfig: CachePolicyConfig;
  Id?: string;
  LastModifiedTime?: string;
}
export interface CachePolicyConfig {
  Comment?: string;
  DefaultTTL: number;
  MaxTTL: number;
  MinTTL: number;
  Name: string;
  ParametersInCacheKeyAndForwardedToOrigin: ParametersInCacheKeyAndForwardedToOrigin;
}
export interface ParametersInCacheKeyAndForwardedToOrigin {
  CookiesConfig: CookiesConfig;
  EnableAcceptEncodingBrotli?: boolean;
  EnableAcceptEncodingGzip: boolean;
  HeadersConfig: HeadersConfig;
  QueryStringsConfig: QueryStringsConfig;
}
export interface CookiesConfig {
  CookieBehavior: string;
  Cookies?: string[];
}
export interface HeadersConfig {
  HeaderBehavior: string;
  Headers?: string[];
}
export interface QueryStringsConfig {
  QueryStringBehavior: string;
  QueryStrings?: string[];
}
