/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::CloudFront::MonitoringSubscription
 */
export interface AwsCloudfrontMonitoringsubscription {
  DistributionId: string;
  MonitoringSubscription: MonitoringSubscription;
}
export interface MonitoringSubscription {
  RealtimeMetricsSubscriptionConfig?: RealtimeMetricsSubscriptionConfig;
}
export interface RealtimeMetricsSubscriptionConfig {
  RealtimeMetricsSubscriptionStatus: "Enabled" | "Disabled";
}
