/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::CloudFront::ResponseHeadersPolicy
 */
export interface AwsCloudfrontResponseheaderspolicy {
  Id?: string;
  LastModifiedTime?: string;
  ResponseHeadersPolicyConfig: ResponseHeadersPolicyConfig;
}
export interface ResponseHeadersPolicyConfig {
  Comment?: string;
  CorsConfig?: CorsConfig;
  CustomHeadersConfig?: CustomHeadersConfig;
  Name: string;
  RemoveHeadersConfig?: RemoveHeadersConfig;
  SecurityHeadersConfig?: SecurityHeadersConfig;
  ServerTimingHeadersConfig?: ServerTimingHeadersConfig;
}
export interface CorsConfig {
  AccessControlAllowCredentials: boolean;
  AccessControlAllowHeaders: AccessControlAllowHeaders;
  AccessControlAllowMethods: AccessControlAllowMethods;
  AccessControlAllowOrigins: AccessControlAllowOrigins;
  AccessControlExposeHeaders?: AccessControlExposeHeaders;
  AccessControlMaxAgeSec?: number;
  OriginOverride: boolean;
}
export interface AccessControlAllowHeaders {
  Items: string[];
}
export interface AccessControlAllowMethods {
  Items: string[];
}
export interface AccessControlAllowOrigins {
  Items: string[];
}
export interface AccessControlExposeHeaders {
  Items: string[];
}
export interface CustomHeadersConfig {
  Items: CustomHeader[];
}
export interface CustomHeader {
  Header: string;
  Override: boolean;
  Value: string;
}
export interface RemoveHeadersConfig {
  Items: RemoveHeader[];
}
export interface RemoveHeader {
  Header: string;
}
export interface SecurityHeadersConfig {
  ContentSecurityPolicy?: ContentSecurityPolicy;
  ContentTypeOptions?: ContentTypeOptions;
  FrameOptions?: FrameOptions;
  ReferrerPolicy?: ReferrerPolicy;
  StrictTransportSecurity?: StrictTransportSecurity;
  XSSProtection?: XSSProtection;
}
export interface ContentSecurityPolicy {
  ContentSecurityPolicy: string;
  Override: boolean;
}
export interface ContentTypeOptions {
  Override: boolean;
}
export interface FrameOptions {
  FrameOption: string;
  Override: boolean;
}
export interface ReferrerPolicy {
  Override: boolean;
  ReferrerPolicy: string;
}
export interface StrictTransportSecurity {
  AccessControlMaxAgeSec: number;
  IncludeSubdomains?: boolean;
  Override: boolean;
  Preload?: boolean;
}
export interface XSSProtection {
  ModeBlock?: boolean;
  Override: boolean;
  Protection: boolean;
  ReportUri?: string;
}
export interface ServerTimingHeadersConfig {
  Enabled: boolean;
  SamplingRate?: number;
}
