/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ApiGatewayV2::DomainName
 */
export interface AwsApigatewayv2Domainname {
  MutualTlsAuthentication?: MutualTlsAuthentication;
  RegionalHostedZoneId?: string;
  RegionalDomainName?: string;
  DomainName: string;
  DomainNameConfigurations?: DomainNameConfiguration[];
  Id?: string;
  Tags?: {
    [k: string]: unknown;
  };
}
export interface MutualTlsAuthentication {
  TruststoreVersion?: string;
  TruststoreUri?: string;
}
export interface DomainNameConfiguration {
  OwnershipVerificationCertificateArn?: string;
  EndpointType?: string;
  CertificateName?: string;
  SecurityPolicy?: string;
  CertificateArn?: string;
}
