/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::FSx::FileSystem
 */
export interface AwsFsxFilesystem {
  StorageType?: string;
  KmsKeyId?: string;
  StorageCapacity?: number;
  RootVolumeId?: string;
  LustreConfiguration?: LustreConfiguration;
  BackupId?: string;
  OntapConfiguration?: OntapConfiguration;
  DNSName?: string;
  SubnetIds: string[];
  SecurityGroupIds?: string[];
  WindowsConfiguration?: WindowsConfiguration;
  FileSystemTypeVersion?: string;
  OpenZFSConfiguration?: OpenZFSConfiguration;
  ResourceARN?: string;
  FileSystemType: string;
  Id?: string;
  LustreMountName?: string;
  Tags?: Tag[];
}
export interface LustreConfiguration {
  DriveCacheType?: string;
  AutoImportPolicy?: string;
  ImportedFileChunkSize?: number;
  DeploymentType?: string;
  DataCompressionType?: string;
  ImportPath?: string;
  WeeklyMaintenanceStartTime?: string;
  DailyAutomaticBackupStartTime?: string;
  CopyTagsToBackups?: boolean;
  ExportPath?: string;
  PerUnitStorageThroughput?: number;
  AutomaticBackupRetentionDays?: number;
}
export interface OntapConfiguration {
  FsxAdminPassword?: string;
  RouteTableIds?: string[];
  WeeklyMaintenanceStartTime?: string;
  DiskIopsConfiguration?: DiskIopsConfiguration;
  DeploymentType: string;
  DailyAutomaticBackupStartTime?: string;
  ThroughputCapacity?: number;
  AutomaticBackupRetentionDays?: number;
  EndpointIpAddressRange?: string;
  PreferredSubnetId?: string;
}
export interface DiskIopsConfiguration {
  Mode?: string;
  Iops?: number;
}
export interface WindowsConfiguration {
  SelfManagedActiveDirectoryConfiguration?: SelfManagedActiveDirectoryConfiguration;
  AuditLogConfiguration?: AuditLogConfiguration;
  WeeklyMaintenanceStartTime?: string;
  ActiveDirectoryId?: string;
  DeploymentType?: string;
  Aliases?: string[];
  ThroughputCapacity: number;
  CopyTagsToBackups?: boolean;
  DailyAutomaticBackupStartTime?: string;
  AutomaticBackupRetentionDays?: number;
  PreferredSubnetId?: string;
}
export interface SelfManagedActiveDirectoryConfiguration {
  FileSystemAdministratorsGroup?: string;
  UserName?: string;
  DomainName?: string;
  OrganizationalUnitDistinguishedName?: string;
  DnsIps?: string[];
  Password?: string;
}
export interface AuditLogConfiguration {
  FileAccessAuditLogLevel: string;
  FileShareAccessAuditLogLevel: string;
  AuditLogDestination?: string;
}
export interface OpenZFSConfiguration {
  Options?: string[];
  WeeklyMaintenanceStartTime?: string;
  DiskIopsConfiguration?: DiskIopsConfiguration;
  CopyTagsToVolumes?: boolean;
  DeploymentType: string;
  DailyAutomaticBackupStartTime?: string;
  CopyTagsToBackups?: boolean;
  ThroughputCapacity?: number;
  RootVolumeConfiguration?: RootVolumeConfiguration;
  AutomaticBackupRetentionDays?: number;
}
export interface RootVolumeConfiguration {
  ReadOnly?: boolean;
  DataCompressionType?: string;
  NfsExports?: NfsExports[];
  CopyTagsToSnapshots?: boolean;
  RecordSizeKiB?: number;
  UserAndGroupQuotas?: UserAndGroupQuotas[];
}
export interface NfsExports {
  ClientConfigurations?: ClientConfigurations[];
}
export interface ClientConfigurations {
  Clients?: string;
  Options?: string[];
}
export interface UserAndGroupQuotas {
  Type?: string;
  Id?: number;
  StorageCapacityQuotaGiB?: number;
}
export interface Tag {
  Value: string;
  Key: string;
}
