/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::FSx::StorageVirtualMachine
 */
export interface AwsFsxStoragevirtualmachine {
  ResourceARN?: string;
  SvmAdminPassword?: string;
  StorageVirtualMachineId?: string;
  ActiveDirectoryConfiguration?: ActiveDirectoryConfiguration;
  RootVolumeSecurityStyle?: string;
  FileSystemId: string;
  UUID?: string;
  Tags?: Tag[];
  Name: string;
}
export interface ActiveDirectoryConfiguration {
  SelfManagedActiveDirectoryConfiguration?: SelfManagedActiveDirectoryConfiguration;
  NetBiosName?: string;
}
export interface SelfManagedActiveDirectoryConfiguration {
  FileSystemAdministratorsGroup?: string;
  UserName?: string;
  DomainName?: string;
  OrganizationalUnitDistinguishedName?: string;
  DnsIps?: string[];
  Password?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
