/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::FSx::Volume
 */
export interface AwsFsxVolume {
  OpenZFSConfiguration?: OpenZFSConfiguration;
  ResourceARN?: string;
  VolumeId?: string;
  VolumeType?: string;
  BackupId?: string;
  OntapConfiguration?: OntapConfiguration;
  UUID?: string;
  Tags?: Tag[];
  Name: string;
}
export interface OpenZFSConfiguration {
  ReadOnly?: boolean;
  Options?: string[];
  DataCompressionType?: string;
  NfsExports?: NfsExports[];
  StorageCapacityQuotaGiB?: number;
  CopyTagsToSnapshots?: boolean;
  ParentVolumeId: string;
  StorageCapacityReservationGiB?: number;
  RecordSizeKiB?: number;
  OriginSnapshot?: OriginSnapshot;
  UserAndGroupQuotas?: UserAndGroupQuotas[];
}
export interface NfsExports {
  ClientConfigurations: ClientConfigurations[];
}
export interface ClientConfigurations {
  Clients: string;
  Options: string[];
}
export interface OriginSnapshot {
  SnapshotARN: string;
  CopyStrategy: string;
}
export interface UserAndGroupQuotas {
  Type: string;
  Id: number;
  StorageCapacityQuotaGiB: number;
}
export interface OntapConfiguration {
  JunctionPath?: string;
  StorageVirtualMachineId: string;
  SnapshotPolicy?: string;
  TieringPolicy?: TieringPolicy;
  StorageEfficiencyEnabled?: string;
  SizeInMegabytes: string;
  CopyTagsToBackups?: string;
  SecurityStyle?: string;
  OntapVolumeType?: string;
}
export interface TieringPolicy {
  CoolingPeriod?: number;
  Name?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
