/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date value in ISO 8601 format. The timezone is always UTC. (YYYY-MM-DDThh:mm:ssZ)
 */
export type Iso8601UTC = string;

/**
 * Resource Type definition for AWS::S3::Bucket
 */
export interface AwsS3Bucket {
  AccelerateConfiguration?: AccelerateConfiguration;
  /**
   * A canned access control list (ACL) that grants predefined permissions to the bucket.
   */
  AccessControl?:
    | "AuthenticatedRead"
    | "AwsExecRead"
    | "BucketOwnerFullControl"
    | "BucketOwnerRead"
    | "LogDeliveryWrite"
    | "Private"
    | "PublicRead"
    | "PublicReadWrite";
  /**
   * The configuration and any analyses for the analytics filter of an Amazon S3 bucket.
   */
  AnalyticsConfigurations?: AnalyticsConfiguration[];
  BucketEncryption?: BucketEncryption;
  /**
   * A name for the bucket. If you don't specify a name, AWS CloudFormation generates a unique physical ID and uses that ID for the bucket name.
   */
  BucketName?: string;
  CorsConfiguration?: CorsConfiguration;
  /**
   * Specifies the S3 Intelligent-Tiering configuration for an Amazon S3 bucket.
   */
  IntelligentTieringConfigurations?: IntelligentTieringConfiguration[];
  /**
   * The inventory configuration for an Amazon S3 bucket.
   */
  InventoryConfigurations?: InventoryConfiguration[];
  LifecycleConfiguration?: LifecycleConfiguration;
  LoggingConfiguration?: LoggingConfiguration;
  /**
   * Settings that define a metrics configuration for the CloudWatch request metrics from the bucket.
   */
  MetricsConfigurations?: MetricsConfiguration[];
  NotificationConfiguration?: NotificationConfiguration;
  ObjectLockConfiguration?: ObjectLockConfiguration;
  /**
   * Indicates whether this bucket has an Object Lock configuration enabled.
   */
  ObjectLockEnabled?: boolean;
  OwnershipControls?: OwnershipControls;
  PublicAccessBlockConfiguration?: PublicAccessBlockConfiguration;
  ReplicationConfiguration?: ReplicationConfiguration;
  /**
   * An arbitrary set of tags (key-value pairs) for this S3 bucket.
   */
  Tags?: Tag[];
  VersioningConfiguration?: VersioningConfiguration;
  WebsiteConfiguration?: WebsiteConfiguration;
  /**
   * The Amazon Resource Name (ARN) of the specified bucket.
   */
  Arn?: string;
  /**
   * The IPv4 DNS name of the specified bucket.
   */
  DomainName?: string;
  /**
   * The IPv6 DNS name of the specified bucket. For more information about dual-stack endpoints, see [Using Amazon S3 Dual-Stack Endpoints](https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html).
   */
  DualStackDomainName?: string;
  /**
   * Returns the regional domain name of the specified bucket.
   */
  RegionalDomainName?: string;
  /**
   * The Amazon S3 website endpoint for the specified bucket.
   */
  WebsiteURL?: string;
}
/**
 * Configuration for the transfer acceleration state.
 */
export interface AccelerateConfiguration {
  /**
   * Configures the transfer acceleration state for an Amazon S3 bucket.
   */
  AccelerationStatus: "Enabled" | "Suspended";
}
/**
 * Specifies the configuration and any analyses for the analytics filter of an Amazon S3 bucket.
 */
export interface AnalyticsConfiguration {
  TagFilters?: TagFilter[];
  StorageClassAnalysis: StorageClassAnalysis;
  /**
   * The ID that identifies the analytics configuration.
   */
  Id: string;
  /**
   * The prefix that an object must have to be included in the analytics results.
   */
  Prefix?: string;
}
/**
 * Tags to use to identify a subset of objects for an Amazon S3 bucket.
 */
export interface TagFilter {
  Value: string;
  Key: string;
}
/**
 * Specifies data related to access patterns to be collected and made available to analyze the tradeoffs between different storage classes for an Amazon S3 bucket.
 */
export interface StorageClassAnalysis {
  DataExport?: DataExport;
}
/**
 * Specifies how data related to the storage class analysis for an Amazon S3 bucket should be exported.
 */
export interface DataExport {
  Destination: Destination;
  /**
   * The version of the output schema to use when exporting data.
   */
  OutputSchemaVersion: "V_1";
}
/**
 * Specifies information about where to publish analysis or configuration results for an Amazon S3 bucket and S3 Replication Time Control (S3 RTC).
 */
export interface Destination {
  /**
   * The Amazon Resource Name (ARN) of the bucket to which data is exported.
   */
  BucketArn: string;
  /**
   * The account ID that owns the destination S3 bucket.
   */
  BucketAccountId?: string;
  /**
   * Specifies the file format used when exporting data to Amazon S3.
   */
  Format: "CSV" | "ORC" | "Parquet";
  /**
   * The prefix to use when exporting data. The prefix is prepended to all results.
   */
  Prefix?: string;
}
/**
 * Specifies default encryption for a bucket using server-side encryption with either Amazon S3-managed keys (SSE-S3) or AWS KMS-managed keys (SSE-KMS).
 */
export interface BucketEncryption {
  /**
   * Specifies the default server-side-encryption configuration.
   */
  ServerSideEncryptionConfiguration: ServerSideEncryptionRule[];
}
/**
 * Specifies the default server-side encryption configuration.
 */
export interface ServerSideEncryptionRule {
  /**
   * Specifies whether Amazon S3 should use an S3 Bucket Key with server-side encryption using KMS (SSE-KMS) for new objects in the bucket. Existing objects are not affected. Setting the BucketKeyEnabled element to true causes Amazon S3 to use an S3 Bucket Key. By default, S3 Bucket Key is not enabled.
   */
  BucketKeyEnabled?: boolean;
  ServerSideEncryptionByDefault?: ServerSideEncryptionByDefault;
}
/**
 * Specifies the default server-side encryption to apply to new objects in the bucket. If a PUT Object request doesn't specify any server-side encryption, this default encryption will be applied.
 */
export interface ServerSideEncryptionByDefault {
  /**
   * "KMSMasterKeyID" can only be used when you set the value of SSEAlgorithm as aws:kms.
   */
  KMSMasterKeyID?: string;
  SSEAlgorithm: "aws:kms" | "AES256";
}
/**
 * Rules that define cross-origin resource sharing of objects in this bucket.
 */
export interface CorsConfiguration {
  CorsRules: CorsRule[];
}
/**
 * A set of origins and methods (cross-origin access that you want to allow). You can add up to 100 rules to the configuration.
 */
export interface CorsRule {
  /**
   * Headers that are specified in the Access-Control-Request-Headers header.
   */
  AllowedHeaders?: string[];
  /**
   * An HTTP method that you allow the origin to execute.
   */
  AllowedMethods: ("GET" | "PUT" | "HEAD" | "POST" | "DELETE")[];
  /**
   * One or more origins you want customers to be able to access the bucket from.
   */
  AllowedOrigins: string[];
  /**
   * One or more headers in the response that you want customers to be able to access from their applications (for example, from a JavaScript XMLHttpRequest object).
   */
  ExposedHeaders?: string[];
  /**
   * A unique identifier for this rule.
   */
  Id?: string;
  /**
   * The time in seconds that your browser is to cache the preflight response for the specified resource.
   */
  MaxAge?: number;
}
export interface IntelligentTieringConfiguration {
  /**
   * The ID used to identify the S3 Intelligent-Tiering configuration.
   */
  Id: string;
  /**
   * An object key name prefix that identifies the subset of objects to which the rule applies.
   */
  Prefix?: string;
  /**
   * Specifies the status of the configuration.
   */
  Status: "Disabled" | "Enabled";
  /**
   * A container for a key-value pair.
   */
  TagFilters?: TagFilter[];
  /**
   * Specifies a list of S3 Intelligent-Tiering storage class tiers in the configuration. At least one tier must be defined in the list. At most, you can specify two tiers in the list, one for each available AccessTier: ARCHIVE_ACCESS and DEEP_ARCHIVE_ACCESS.
   */
  Tierings: Tiering[];
}
export interface Tiering {
  /**
   * S3 Intelligent-Tiering access tier. See Storage class for automatically optimizing frequently and infrequently accessed objects for a list of access tiers in the S3 Intelligent-Tiering storage class.
   */
  AccessTier: "ARCHIVE_ACCESS" | "DEEP_ARCHIVE_ACCESS";
  /**
   * The number of consecutive days of no access after which an object will be eligible to be transitioned to the corresponding tier. The minimum number of days specified for Archive Access tier must be at least 90 days and Deep Archive Access tier must be at least 180 days. The maximum can be up to 2 years (730 days).
   */
  Days: number;
}
export interface InventoryConfiguration {
  Destination: Destination;
  /**
   * Specifies whether the inventory is enabled or disabled.
   */
  Enabled: boolean;
  /**
   * The ID used to identify the inventory configuration.
   */
  Id: string;
  /**
   * Object versions to include in the inventory list.
   */
  IncludedObjectVersions: "All" | "Current";
  /**
   * Contains the optional fields that are included in the inventory results.
   */
  OptionalFields?: (
    | "Size"
    | "LastModifiedDate"
    | "StorageClass"
    | "ETag"
    | "IsMultipartUploaded"
    | "ReplicationStatus"
    | "EncryptionStatus"
    | "ObjectLockRetainUntilDate"
    | "ObjectLockMode"
    | "ObjectLockLegalHoldStatus"
    | "IntelligentTieringAccessTier"
    | "BucketKeyStatus"
  )[];
  /**
   * The prefix that is prepended to all inventory results.
   */
  Prefix?: string;
  /**
   * Specifies the schedule for generating inventory results.
   */
  ScheduleFrequency: "Daily" | "Weekly";
}
/**
 * Rules that define how Amazon S3 manages objects during their lifetime.
 */
export interface LifecycleConfiguration {
  /**
   * A lifecycle rule for individual objects in an Amazon S3 bucket.
   */
  Rules: Rule[];
}
/**
 * You must specify at least one of the following properties: AbortIncompleteMultipartUpload, ExpirationDate, ExpirationInDays, NoncurrentVersionExpirationInDays, NoncurrentVersionTransition, NoncurrentVersionTransitions, Transition, or Transitions.
 */
export interface Rule {
  AbortIncompleteMultipartUpload?: AbortIncompleteMultipartUpload;
  ExpirationDate?: Iso8601UTC;
  ExpirationInDays?: number;
  ExpiredObjectDeleteMarker?: boolean;
  Id?: string;
  NoncurrentVersionExpirationInDays?: number;
  NoncurrentVersionExpiration?: NoncurrentVersionExpiration;
  NoncurrentVersionTransition?: NoncurrentVersionTransition;
  NoncurrentVersionTransitions?: NoncurrentVersionTransition[];
  Prefix?: string;
  Status: "Enabled" | "Disabled";
  TagFilters?: TagFilter[];
  ObjectSizeGreaterThan?: string;
  ObjectSizeLessThan?: string;
  Transition?: Transition;
  Transitions?: Transition[];
}
/**
 * Specifies the days since the initiation of an incomplete multipart upload that Amazon S3 will wait before permanently removing all parts of the upload.
 */
export interface AbortIncompleteMultipartUpload {
  /**
   * Specifies the number of days after which Amazon S3 aborts an incomplete multipart upload.
   */
  DaysAfterInitiation: number;
}
/**
 * Container for the expiration rule that describes when noncurrent objects are expired. If your bucket is versioning-enabled (or versioning is suspended), you can set this action to request that Amazon S3 expire noncurrent object versions at a specific period in the object's lifetime
 */
export interface NoncurrentVersionExpiration {
  /**
   * Specified the number of days an object is noncurrent before Amazon S3 can perform the associated action
   */
  NoncurrentDays: number;
  /**
   * Specified the number of newer noncurrent and current versions that must exists before performing the associated action
   */
  NewerNoncurrentVersions?: number;
}
/**
 * Container for the transition rule that describes when noncurrent objects transition to the STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, GLACIER_IR, GLACIER, or DEEP_ARCHIVE storage class. If your bucket is versioning-enabled (or versioning is suspended), you can set this action to request that Amazon S3 transition noncurrent object versions to the STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, GLACIER_IR, GLACIER, or DEEP_ARCHIVE storage class at a specific period in the object's lifetime.
 */
export interface NoncurrentVersionTransition {
  /**
   * The class of storage used to store the object.
   */
  StorageClass:
    | "DEEP_ARCHIVE"
    | "GLACIER"
    | "Glacier"
    | "GLACIER_IR"
    | "INTELLIGENT_TIERING"
    | "ONEZONE_IA"
    | "STANDARD_IA";
  /**
   * Specifies the number of days an object is noncurrent before Amazon S3 can perform the associated action.
   */
  TransitionInDays: number;
  /**
   * Specified the number of newer noncurrent and current versions that must exists before performing the associated action
   */
  NewerNoncurrentVersions?: number;
}
/**
 * You must specify at least one of "TransitionDate" and "TransitionInDays"
 */
export interface Transition {
  StorageClass:
    | "DEEP_ARCHIVE"
    | "GLACIER"
    | "Glacier"
    | "GLACIER_IR"
    | "INTELLIGENT_TIERING"
    | "ONEZONE_IA"
    | "STANDARD_IA";
  TransitionDate?: Iso8601UTC;
  TransitionInDays?: number;
}
/**
 * Settings that define where logs are stored.
 */
export interface LoggingConfiguration {
  /**
   * The name of an Amazon S3 bucket where Amazon S3 store server access log files. You can store log files in any bucket that you own. By default, logs are stored in the bucket where the LoggingConfiguration property is defined.
   */
  DestinationBucketName?: string;
  LogFilePrefix?: string;
}
export interface MetricsConfiguration {
  AccessPointArn?: string;
  Id: string;
  Prefix?: string;
  TagFilters?: TagFilter[];
}
/**
 * Configuration that defines how Amazon S3 handles bucket notifications.
 */
export interface NotificationConfiguration {
  EventBridgeConfiguration?: EventBridgeConfiguration;
  LambdaConfigurations?: LambdaConfiguration[];
  QueueConfigurations?: QueueConfiguration[];
  TopicConfigurations?: TopicConfiguration[];
}
/**
 * Describes the Amazon EventBridge notification configuration for an Amazon S3 bucket.
 */
export interface EventBridgeConfiguration {
  /**
   * Specifies whether to send notifications to Amazon EventBridge when events occur in an Amazon S3 bucket.
   */
  EventBridgeEnabled: boolean & string;
}
/**
 * Describes the AWS Lambda functions to invoke and the events for which to invoke them.
 */
export interface LambdaConfiguration {
  /**
   * The Amazon S3 bucket event for which to invoke the AWS Lambda function.
   */
  Event: string;
  Filter?: NotificationFilter;
  /**
   * The Amazon Resource Name (ARN) of the AWS Lambda function that Amazon S3 invokes when the specified event type occurs.
   */
  Function: string;
}
/**
 * The filtering rules that determine which objects invoke the AWS Lambda function.
 */
export interface NotificationFilter {
  S3Key: S3KeyFilter;
}
/**
 * A container for object key name prefix and suffix filtering rules.
 */
export interface S3KeyFilter {
  Rules: FilterRule[];
}
/**
 * Specifies the Amazon S3 object key name to filter on and whether to filter on the suffix or prefix of the key name.
 */
export interface FilterRule {
  Name: string;
  Value: string;
}
/**
 * The Amazon Simple Queue Service queues to publish messages to and the events for which to publish messages.
 */
export interface QueueConfiguration {
  /**
   * The Amazon S3 bucket event about which you want to publish messages to Amazon SQS.
   */
  Event: string;
  Filter?: NotificationFilter1;
  /**
   * The Amazon Resource Name (ARN) of the Amazon SQS queue to which Amazon S3 publishes a message when it detects events of the specified type.
   */
  Queue: string;
}
/**
 * The filtering rules that determine which objects trigger notifications.
 */
export interface NotificationFilter1 {
  S3Key: S3KeyFilter;
}
/**
 * The topic to which notifications are sent and the events for which notifications are generated.
 */
export interface TopicConfiguration {
  /**
   * The Amazon S3 bucket event about which to send notifications.
   */
  Event: string;
  Filter?: NotificationFilter2;
  /**
   * The Amazon Resource Name (ARN) of the Amazon SNS topic to which Amazon S3 publishes a message when it detects events of the specified type.
   */
  Topic: string;
}
/**
 * The filtering rules that determine for which objects to send notifications.
 */
export interface NotificationFilter2 {
  S3Key: S3KeyFilter;
}
/**
 * Places an Object Lock configuration on the specified bucket.
 */
export interface ObjectLockConfiguration {
  ObjectLockEnabled?: "Enabled";
  Rule?: ObjectLockRule;
}
/**
 * The Object Lock rule in place for the specified object.
 */
export interface ObjectLockRule {
  DefaultRetention?: DefaultRetention;
}
/**
 * The default retention period that you want to apply to new objects placed in the specified bucket.
 */
export interface DefaultRetention {
  Years?: number;
  Days?: number;
  Mode?: "COMPLIANCE" | "GOVERNANCE";
}
/**
 * Specifies the container element for object ownership rules.
 */
export interface OwnershipControls {
  Rules: OwnershipControlsRule[];
}
export interface OwnershipControlsRule {
  /**
   * Specifies an object ownership rule.
   */
  ObjectOwnership?: "ObjectWriter" | "BucketOwnerPreferred" | "BucketOwnerEnforced";
}
/**
 * Configuration that defines how Amazon S3 handles public access.
 */
export interface PublicAccessBlockConfiguration {
  /**
   * Specifies whether Amazon S3 should block public access control lists (ACLs) for this bucket and objects in this bucket. Setting this element to TRUE causes the following behavior:
   * - PUT Bucket acl and PUT Object acl calls fail if the specified ACL is public.
   *  - PUT Object calls fail if the request includes a public ACL.
   * Enabling this setting doesn't affect existing policies or ACLs.
   */
  BlockPublicAcls?: boolean;
  /**
   * Specifies whether Amazon S3 should block public bucket policies for this bucket. Setting this element to TRUE causes Amazon S3 to reject calls to PUT Bucket policy if the specified bucket policy allows public access.
   * Enabling this setting doesn't affect existing bucket policies.
   */
  BlockPublicPolicy?: boolean;
  /**
   * Specifies whether Amazon S3 should ignore public ACLs for this bucket and objects in this bucket. Setting this element to TRUE causes Amazon S3 to ignore all public ACLs on this bucket and objects in this bucket.
   * Enabling this setting doesn't affect the persistence of any existing ACLs and doesn't prevent new public ACLs from being set.
   */
  IgnorePublicAcls?: boolean;
  /**
   * Specifies whether Amazon S3 should restrict public bucket policies for this bucket. Setting this element to TRUE restricts access to this bucket to only AWS services and authorized users within this account if the bucket has a public policy.
   * Enabling this setting doesn't affect previously stored bucket policies, except that public and cross-account access within any public bucket policy, including non-public delegation to specific accounts, is blocked.
   */
  RestrictPublicBuckets?: boolean;
}
/**
 * Configuration for replicating objects in an S3 bucket.
 */
export interface ReplicationConfiguration {
  /**
   * The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that Amazon S3 assumes when replicating objects.
   */
  Role: string;
  /**
   * A container for one or more replication rules.
   */
  Rules: ReplicationRule[];
}
/**
 * Specifies which Amazon S3 objects to replicate and where to store the replicas.
 */
export interface ReplicationRule {
  DeleteMarkerReplication?: DeleteMarkerReplication;
  Destination: ReplicationDestination;
  Filter?: ReplicationRuleFilter;
  /**
   * A unique identifier for the rule.
   */
  Id?: string;
  /**
   * An object key name prefix that identifies the object or objects to which the rule applies.
   */
  Prefix?: string;
  Priority?: number;
  SourceSelectionCriteria?: SourceSelectionCriteria;
  /**
   * Specifies whether the rule is enabled.
   */
  Status: "Disabled" | "Enabled";
}
export interface DeleteMarkerReplication {
  Status?: "Disabled" | "Enabled";
}
/**
 * Specifies which Amazon S3 bucket to store replicated objects in and their storage class.
 */
export interface ReplicationDestination {
  AccessControlTranslation?: AccessControlTranslation;
  Account?: string;
  Bucket: string;
  EncryptionConfiguration?: EncryptionConfiguration;
  Metrics?: Metrics;
  ReplicationTime?: ReplicationTime;
  /**
   * The storage class to use when replicating objects, such as S3 Standard or reduced redundancy.
   */
  StorageClass?:
    | "DEEP_ARCHIVE"
    | "GLACIER"
    | "GLACIER_IR"
    | "INTELLIGENT_TIERING"
    | "ONEZONE_IA"
    | "REDUCED_REDUNDANCY"
    | "STANDARD"
    | "STANDARD_IA";
}
/**
 * Specify this only in a cross-account scenario (where source and destination bucket owners are not the same), and you want to change replica ownership to the AWS account that owns the destination bucket. If this is not specified in the replication configuration, the replicas are owned by same AWS account that owns the source object.
 */
export interface AccessControlTranslation {
  Owner: "Destination";
}
/**
 * Specifies encryption-related information for an Amazon S3 bucket that is a destination for replicated objects.
 */
export interface EncryptionConfiguration {
  /**
   * Specifies the ID (Key ARN or Alias ARN) of the customer managed customer master key (CMK) stored in AWS Key Management Service (KMS) for the destination bucket.
   */
  ReplicaKmsKeyID: string;
}
export interface Metrics {
  EventThreshold?: ReplicationTimeValue;
  Status: "Disabled" | "Enabled";
}
export interface ReplicationTimeValue {
  Minutes: number;
}
export interface ReplicationTime {
  Status: "Disabled" | "Enabled";
  Time: ReplicationTimeValue;
}
export interface ReplicationRuleFilter {
  And?: ReplicationRuleAndOperator;
  Prefix?: string;
  TagFilter?: TagFilter;
}
export interface ReplicationRuleAndOperator {
  Prefix?: string;
  TagFilters?: TagFilter[];
}
/**
 * A container that describes additional filters for identifying the source objects that you want to replicate.
 */
export interface SourceSelectionCriteria {
  ReplicaModifications?: ReplicaModifications;
  SseKmsEncryptedObjects?: SseKmsEncryptedObjects;
}
/**
 * A filter that you can specify for selection for modifications on replicas.
 */
export interface ReplicaModifications {
  /**
   * Specifies whether Amazon S3 replicates modifications on replicas.
   */
  Status: "Enabled" | "Disabled";
}
/**
 * A container for filter information for the selection of Amazon S3 objects encrypted with AWS KMS.
 */
export interface SseKmsEncryptedObjects {
  /**
   * Specifies whether Amazon S3 replicates objects created with server-side encryption using a customer master key (CMK) stored in AWS Key Management Service.
   */
  Status: "Disabled" | "Enabled";
}
export interface Tag {
  Key: string;
  Value: string;
}
/**
 * Describes the versioning state of an Amazon S3 bucket.
 */
export interface VersioningConfiguration {
  /**
   * The versioning state of the bucket.
   */
  Status: "Enabled" | "Suspended";
}
/**
 * Specifies website configuration parameters for an Amazon S3 bucket.
 */
export interface WebsiteConfiguration {
  /**
   * The name of the error document for the website.
   */
  ErrorDocument?: string;
  /**
   * The name of the index document for the website.
   */
  IndexDocument?: string;
  RoutingRules?: RoutingRule[];
  RedirectAllRequestsTo?: RedirectAllRequestsTo;
}
/**
 * Specifies the redirect behavior and when a redirect is applied.
 */
export interface RoutingRule {
  RedirectRule: RedirectRule;
  RoutingRuleCondition?: RoutingRuleCondition;
}
/**
 * Container for redirect information. You can redirect requests to another host, to another page, or with another protocol. In the event of an error, you can specify a different error code to return.
 */
export interface RedirectRule {
  /**
   * The host name to use in the redirect request.
   */
  HostName?: string;
  /**
   * The HTTP redirect code to use on the response. Not required if one of the siblings is present.
   */
  HttpRedirectCode?: string;
  /**
   * Protocol to use when redirecting requests. The default is the protocol that is used in the original request.
   */
  Protocol?: "http" | "https";
  /**
   * The object key prefix to use in the redirect request.
   */
  ReplaceKeyPrefixWith?: string;
  /**
   * The specific object key to use in the redirect request.d
   */
  ReplaceKeyWith?: string;
}
/**
 * A container for describing a condition that must be met for the specified redirect to apply.You must specify at least one of HttpErrorCodeReturnedEquals and KeyPrefixEquals
 */
export interface RoutingRuleCondition {
  /**
   * The object key name prefix when the redirect is applied.
   */
  KeyPrefixEquals?: string;
  /**
   * The HTTP error code when the redirect is applied.
   */
  HttpErrorCodeReturnedEquals?: string;
}
/**
 * Specifies the redirect behavior of all requests to a website endpoint of an Amazon S3 bucket.
 */
export interface RedirectAllRequestsTo {
  /**
   * Name of the host where requests are redirected.
   */
  HostName: string;
  /**
   * Protocol to use when redirecting requests. The default is the protocol that is used in the original request.
   */
  Protocol?: "http" | "https";
}
