/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ElastiCache::CacheCluster
 */
export interface AwsElasticacheCachecluster {
  CacheSecurityGroupNames?: string[];
  SnapshotArns?: string[];
  Port?: number;
  ConfigurationEndpointAddress?: string;
  NotificationTopicArn?: string;
  NumCacheNodes: number;
  SnapshotName?: string;
  TransitEncryptionEnabled?: boolean;
  NetworkType?: string;
  PreferredAvailabilityZones?: string[];
  VpcSecurityGroupIds?: string[];
  ClusterName?: string;
  RedisEndpointAddress?: string;
  Engine: string;
  Tags?: Tag[];
  EngineVersion?: string;
  RedisEndpointPort?: string;
  CacheSubnetGroupName?: string;
  CacheParameterGroupName?: string;
  PreferredMaintenanceWindow?: string;
  AutoMinorVersionUpgrade?: boolean;
  PreferredAvailabilityZone?: string;
  SnapshotWindow?: string;
  CacheNodeType: string;
  SnapshotRetentionLimit?: number;
  ConfigurationEndpointPort?: string;
  IpDiscovery?: string;
  LogDeliveryConfigurations?: LogDeliveryConfigurationRequest[];
  Id?: string;
  AZMode?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface LogDeliveryConfigurationRequest {
  LogType: string;
  LogFormat: string;
  DestinationType: string;
  DestinationDetails: DestinationDetails;
}
export interface DestinationDetails {
  CloudWatchLogsDetails?: CloudWatchLogsDestinationDetails;
  KinesisFirehoseDetails?: KinesisFirehoseDestinationDetails;
}
export interface CloudWatchLogsDestinationDetails {
  LogGroup: string;
}
export interface KinesisFirehoseDestinationDetails {
  DeliveryStream: string;
}
