/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ElasticBeanstalk::ApplicationVersion
 */
export interface AwsElasticbeanstalkApplicationversion {
  Id?: string;
  /**
   * The name of the Elastic Beanstalk application that is associated with this application version.
   */
  ApplicationName: string;
  /**
   * A description of this application version.
   */
  Description?: string;
  SourceBundle: SourceBundle;
}
/**
 * The Amazon S3 bucket and key that identify the location of the source bundle for this version.
 */
export interface SourceBundle {
  /**
   * The Amazon S3 bucket where the data is located.
   */
  S3Bucket: string;
  /**
   * The Amazon S3 key where the data is located.
   */
  S3Key: string;
}
