/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::IVS::PlaybackKeyPair
 */
export interface AwsIvsPlaybackkeypair {
  /**
   * An arbitrary string (a nickname) assigned to a playback key pair that helps the customer identify that resource. The value does not need to be unique.
   */
  Name?: string;
  /**
   * The public portion of a customer-generated key pair.
   */
  PublicKeyMaterial?: string;
  /**
   * Key-pair identifier.
   */
  Fingerprint?: string;
  /**
   * Key-pair identifier.
   */
  Arn?: string;
  /**
   * A list of key-value pairs that contain metadata for the asset model.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
}
export interface Tag {
  Key: string;
  Value: string;
}
