/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::IVS::StreamKey
 */
export interface AwsIvsStreamkey {
  /**
   * Stream Key ARN is automatically generated on creation and assigned as the unique identifier.
   */
  Arn?: string;
  /**
   * Channel ARN for the stream.
   */
  ChannelArn: string;
  /**
   * A list of key-value pairs that contain metadata for the asset model.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
  /**
   * Stream-key value.
   */
  Value?: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
