/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tunnel protocol type (Only support GRE for now)
 */
export type TunnelProtocol = string;

/**
 * AWS::NetworkManager::ConnectPeer Resource Type Definition.
 */
export interface AwsNetworkmanagerConnectpeer {
  /**
   * The IP address of the Connect peer.
   */
  PeerAddress: string;
  /**
   * The IP address of a core network.
   */
  CoreNetworkAddress?: string;
  BgpOptions?: BgpOptions;
  /**
   * The inside IP addresses used for a Connect peer configuration.
   */
  InsideCidrBlocks: string[];
  /**
   * The ID of the core network.
   */
  CoreNetworkId?: string;
  /**
   * The ID of the attachment to connect.
   */
  ConnectAttachmentId: string;
  /**
   * The ID of the Connect peer.
   */
  ConnectPeerId?: string;
  /**
   * The Connect peer Regions where edges are located.
   */
  EdgeLocation?: string;
  /**
   * State of the connect peer.
   */
  State?: string;
  /**
   * Connect peer creation time.
   */
  CreatedAt?: string;
  Configuration?: ConnectPeerConfiguration;
  /**
   * An array of key-value pairs to apply to this resource.
   */
  Tags?: Tag[];
}
/**
 * Bgp options for connect peer.
 */
export interface BgpOptions {
  PeerAsn?: number;
}
/**
 * Configuration of the connect peer.
 */
export interface ConnectPeerConfiguration {
  CoreNetworkAddress?: string;
  PeerAddress?: string;
  InsideCidrBlocks?: string[];
  Protocol?: TunnelProtocol;
  BgpConfigurations?: ConnectPeerBgpConfiguration[];
}
/**
 * Bgp configuration for connect peer
 */
export interface ConnectPeerBgpConfiguration {
  CoreNetworkAsn?: number;
  PeerAsn?: number;
  CoreNetworkAddress?: string;
  PeerAddress?: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
