/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AWS::NetworkManager::CoreNetwork Resource Type Definition.
 */
export interface AwsNetworkmanagerCorenetwork {
  /**
   * The ID of the global network that your core network is a part of.
   */
  GlobalNetworkId: string;
  /**
   * The Id of core network
   */
  CoreNetworkId?: string;
  /**
   * The ARN (Amazon resource name) of core network
   */
  CoreNetworkArn?: string;
  /**
   * Live policy document for the core network, you must provide PolicyDocument in Json Format
   */
  PolicyDocument?: {
    [k: string]: unknown;
  };
  /**
   * The description of core network
   */
  Description?: string;
  /**
   * The creation time of core network
   */
  CreatedAt?: string;
  /**
   * The state of core network
   */
  State?: string;
  /**
   * The segments within a core network.
   */
  Segments?: CoreNetworkSegment[];
  /**
   * The edges within a core network.
   */
  Edges?: CoreNetworkEdge[];
  /**
   * Owner of the core network
   */
  OwnerAccount?: string;
  /**
   * The tags for the global network.
   */
  Tags?: Tag[];
}
export interface CoreNetworkSegment {
  /**
   * Name of segment
   */
  Name?: string;
  EdgeLocations?: string[];
  SharedSegments?: string[];
}
export interface CoreNetworkEdge {
  /**
   * The Region where a core network edge is located.
   */
  EdgeLocation?: string;
  /**
   * The ASN of a core network edge.
   */
  Asn?: number;
  InsideCidrBlocks?: string[];
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
