/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AWS::NetworkManager::SiteToSiteVpnAttachment Resource Type definition.
 */
export interface AwsNetworkmanagerSitetositevpnattachment {
  /**
   * The ID of a core network where you're creating a site-to-site VPN attachment.
   */
  CoreNetworkId: string;
  /**
   * The ARN of a core network for the VPC attachment.
   */
  CoreNetworkArn?: string;
  /**
   * The ID of the attachment.
   */
  AttachmentId?: string;
  /**
   * Owner account of the attachment.
   */
  OwnerAccountId?: string;
  /**
   * The type of attachment.
   */
  AttachmentType?: string;
  /**
   * The state of the attachment.
   */
  State?: string;
  /**
   * The Region where the edge is located.
   */
  EdgeLocation?: string;
  /**
   * The ARN of the Resource.
   */
  ResourceArn?: string;
  /**
   * The policy rule number associated with the attachment.
   */
  AttachmentPolicyRuleNumber?: number;
  /**
   * The name of the segment that attachment is in.
   */
  SegmentName?: string;
  ProposedSegmentChange?: ProposedSegmentChange;
  /**
   * Tags for the attachment.
   */
  Tags?: Tag[];
  /**
   * Creation time of the attachment.
   */
  CreatedAt?: string;
  /**
   * Last update time of the attachment.
   */
  UpdatedAt?: string;
  /**
   * The ARN of the site-to-site VPN attachment.
   */
  VpnConnectionArn: string;
}
/**
 * The attachment to move from one segment to another.
 */
export interface ProposedSegmentChange {
  /**
   * The key-value tags that changed for the segment.
   */
  Tags?: Tag[];
  /**
   * The rule number in the policy document that applies to this change.
   */
  AttachmentPolicyRuleNumber?: number;
  /**
   * The name of the segment to change.
   */
  SegmentName?: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
