/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::CodeCommit::Repository
 */
export interface AwsCodecommitRepository {
  CloneUrlHttp?: string;
  CloneUrlSsh?: string;
  RepositoryName: string;
  Triggers?: RepositoryTrigger[];
  Id?: string;
  Arn?: string;
  Code?: Code;
  RepositoryDescription?: string;
  Tags?: Tag[];
  Name?: string;
}
export interface RepositoryTrigger {
  CustomData?: string;
  Events: string[];
  Branches?: string[];
  DestinationArn: string;
  Name: string;
}
export interface Code {
  S3: S3;
  BranchName?: string;
}
export interface S3 {
  ObjectVersion?: string;
  Bucket: string;
  Key: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
