/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique ID of the FAQ
 */
export type Id = string;
export type S3BucketName = string;
export type S3ObjectKey = string;
/**
 * Tags for labeling the FAQ
 *
 * @maxItems 200
 */
export type TagList = Tag[];

/**
 * A Kendra FAQ resource
 */
export interface AwsKendraFaq {
  Id?: Id;
  /**
   * Index ID
   */
  IndexId: string;
  /**
   * FAQ name
   */
  Name: string;
  /**
   * FAQ description
   */
  Description?: string;
  /**
   * FAQ file format
   */
  FileFormat?: "CSV" | "CSV_WITH_HEADER" | "JSON";
  S3Path: S3Path;
  /**
   * FAQ role ARN
   */
  RoleArn: string;
  Tags?: TagList;
  Arn?: string;
}
/**
 * FAQ S3 path
 */
export interface S3Path {
  Bucket: S3BucketName;
  Key: S3ObjectKey;
}
/**
 * A label for tagging Kendra resources
 */
export interface Tag {
  /**
   * A string used to identify this tag
   */
  Key: string;
  /**
   * A string containing the value for the tag
   */
  Value: string;
}
