/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Subscription ARN
 */
export type Arn = string;

/**
 * AWS Cost Anomaly Detection leverages advanced Machine Learning technologies to identify anomalous spend and root causes, so you can quickly take action. Create subscription to be notified
 */
export interface AwsCeAnomalysubscription {
  SubscriptionArn?: Arn;
  /**
   * The name of the subscription.
   */
  SubscriptionName: string;
  /**
   * The accountId
   */
  AccountId?: string;
  /**
   * A list of cost anomaly monitors.
   */
  MonitorArnList: Arn[];
  /**
   * A list of subscriber
   */
  Subscribers: Subscriber[];
  /**
   * The dollar value that triggers a notification if the threshold is exceeded.
   */
  Threshold?: number;
  /**
   * An Expression object in JSON String format used to specify the anomalies that you want to generate alerts for.
   */
  ThresholdExpression?: string;
  /**
   * The frequency at which anomaly reports are sent over email.
   */
  Frequency: "DAILY" | "IMMEDIATE" | "WEEKLY";
  /**
   * Tags to assign to subscription.
   *
   * @minItems 0
   * @maxItems 200
   */
  ResourceTags?: ResourceTag[];
}
export interface Subscriber {
  Address: string;
  Status?: "CONFIRMED" | "DECLINED";
  Type: "EMAIL" | "SNS";
}
/**
 * A key-value pair to associate with a resource.
 */
export interface ResourceTag {
  /**
   * The key name for the tag.
   */
  Key: string;
  /**
   * The value for the tag.
   */
  Value: string;
}
