/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::CertificateManager::Certificate
 */
export interface AwsCertificatemanagerCertificate {
  CertificateAuthorityArn?: string;
  DomainValidationOptions?: DomainValidationOption[];
  CertificateTransparencyLoggingPreference?: string;
  DomainName: string;
  ValidationMethod?: string;
  SubjectAlternativeNames?: string[];
  Id?: string;
  Tags?: Tag[];
}
export interface DomainValidationOption {
  DomainName: string;
  ValidationDomain?: string;
  HostedZoneId?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
