/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AWS Route53 Recovery Control Control Panel resource schema .
 */
export interface AwsRoute53RecoverycontrolControlpanel {
  /**
   * Cluster to associate with the Control Panel
   */
  ClusterArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the cluster.
   */
  ControlPanelArn?: string;
  /**
   * The name of the control panel. You can use any non-white space character in the name.
   */
  Name: string;
  /**
   * The deployment status of control panel. Status can be one of the following: PENDING, DEPLOYED, PENDING_DELETION.
   */
  Status?: "PENDING" | "DEPLOYED" | "PENDING_DELETION";
  /**
   * A flag that Amazon Route 53 Application Recovery Controller sets to true to designate the default control panel for a cluster. When you create a cluster, Amazon Route 53 Application Recovery Controller creates a control panel, and sets this flag for that control panel. If you create a control panel yourself, this flag is set to false.
   */
  DefaultControlPanel?: boolean;
  /**
   * Count of associated routing controls
   */
  RoutingControlCount?: number;
  /**
   * A collection of tags associated with a resource
   */
  Tags?: Tag[];
}
export interface Tag {
  Key: string;
  Value: string;
}
