/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Kinesis::Stream
 */
export interface AwsKinesisStream {
  StreamModeDetails?: StreamModeDetails;
  StreamEncryption?: StreamEncryption;
  /**
   * The Amazon resource name (ARN) of the Kinesis stream
   */
  Arn?: string;
  /**
   * The number of hours for the data records that are stored in shards to remain accessible.
   */
  RetentionPeriodHours?: number;
  /**
   * An arbitrary set of tags (key–value pairs) to associate with the Kinesis stream.
   */
  Tags?: Tag[];
  /**
   * The name of the Kinesis stream.
   */
  Name?: string;
  /**
   * The number of shards that the stream uses. Required when StreamMode = PROVISIONED is passed.
   */
  ShardCount?: number;
}
/**
 * The mode in which the stream is running.
 */
export interface StreamModeDetails {
  /**
   * The mode of the stream
   */
  StreamMode: "ON_DEMAND" | "PROVISIONED";
}
/**
 * When specified, enables or updates server-side encryption using an AWS KMS key for a specified stream.
 */
export interface StreamEncryption {
  /**
   * The encryption type to use. The only valid value is KMS.
   */
  EncryptionType: "KMS";
  /**
   * The GUID for the customer-managed AWS KMS key to use for encryption. This value can be a globally unique identifier, a fully specified Amazon Resource Name (ARN) to either an alias or a key, or an alias name prefixed by "alias/".You can also use a master key owned by Kinesis Data Streams by specifying the alias aws/kinesis.
   */
  KeyId: string;
}
/**
 * An arbitrary set of tags (key-value pairs) to associate with the Kinesis stream.
 */
export interface Tag {
  /**
   * The value for the tag. You can specify a value that is 0 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
}
