/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::IAM::User
 */
export interface AwsIamUser {
  Path?: string;
  ManagedPolicyArns?: string[];
  Policies?: Policy[];
  UserName?: string;
  Groups?: string[];
  Id?: string;
  Arn?: string;
  LoginProfile?: LoginProfile;
  Tags?: Tag[];
  PermissionsBoundary?: string;
}
export interface Policy {
  PolicyDocument: {
    [k: string]: unknown;
  };
  PolicyName: string;
}
export interface LoginProfile {
  PasswordResetRequired?: boolean;
  Password: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
