/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Use a SecurityConfiguration resource to configure data encryption, Kerberos authentication, and Amazon S3 authorization for EMRFS.
 */
export interface AwsEmrSecurityconfiguration {
  /**
   * The name of the security configuration.
   */
  Name?: string;
  /**
   * The security configuration details in JSON format.
   */
  SecurityConfiguration:
    | {
        [k: string]: unknown;
      }
    | string;
}
