/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Glue::DataCatalogEncryptionSettings
 */
export interface AwsGlueDatacatalogencryptionsettings {
  Id?: string;
  DataCatalogEncryptionSettings: DataCatalogEncryptionSettings;
  CatalogId: string;
}
export interface DataCatalogEncryptionSettings {
  ConnectionPasswordEncryption?: ConnectionPasswordEncryption;
  EncryptionAtRest?: EncryptionAtRest;
}
export interface ConnectionPasswordEncryption {
  ReturnConnectionPasswordEncrypted?: boolean;
  KmsKeyId?: string;
}
export interface EncryptionAtRest {
  CatalogEncryptionMode?: string;
  SseAwsKmsKeyId?: string;
}
