/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Glue::Partition
 */
export interface AwsGluePartition {
  DatabaseName: string;
  TableName: string;
  Id?: string;
  CatalogId: string;
  PartitionInput: PartitionInput;
}
export interface PartitionInput {
  StorageDescriptor?: StorageDescriptor;
  Values: string[];
  Parameters?: {
    [k: string]: unknown;
  };
}
export interface StorageDescriptor {
  StoredAsSubDirectories?: boolean;
  Parameters?: {
    [k: string]: unknown;
  };
  BucketColumns?: string[];
  NumberOfBuckets?: number;
  OutputFormat?: string;
  Columns?: Column[];
  SerdeInfo?: SerdeInfo;
  SortColumns?: Order[];
  Compressed?: boolean;
  SchemaReference?: SchemaReference;
  SkewedInfo?: SkewedInfo;
  InputFormat?: string;
  Location?: string;
}
export interface Column {
  Comment?: string;
  Type?: string;
  Name: string;
}
export interface SerdeInfo {
  Parameters?: {
    [k: string]: unknown;
  };
  SerializationLibrary?: string;
  Name?: string;
}
export interface Order {
  Column: string;
  SortOrder?: number;
}
export interface SchemaReference {
  SchemaId?: SchemaId;
  SchemaVersionId?: string;
  SchemaVersionNumber?: number;
}
export interface SchemaId {
  RegistryName?: string;
  SchemaName?: string;
  SchemaArn?: string;
}
export interface SkewedInfo {
  SkewedColumnValues?: string[];
  SkewedColumnValueLocationMaps?: {
    [k: string]: unknown;
  };
  SkewedColumnNames?: string[];
}
