/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Glue::Table
 */
export interface AwsGlueTable {
  DatabaseName: string;
  TableInput: TableInput;
  Id?: string;
  CatalogId: string;
}
export interface TableInput {
  Owner?: string;
  ViewOriginalText?: string;
  Description?: string;
  TableType?: string;
  Parameters?: {
    [k: string]: unknown;
  };
  ViewExpandedText?: string;
  StorageDescriptor?: StorageDescriptor;
  TargetTable?: TableIdentifier;
  PartitionKeys?: Column[];
  Retention?: number;
  Name?: string;
}
export interface StorageDescriptor {
  StoredAsSubDirectories?: boolean;
  Parameters?: {
    [k: string]: unknown;
  };
  BucketColumns?: string[];
  NumberOfBuckets?: number;
  OutputFormat?: string;
  Columns?: Column[];
  SerdeInfo?: SerdeInfo;
  SortColumns?: Order[];
  Compressed?: boolean;
  SchemaReference?: SchemaReference;
  SkewedInfo?: SkewedInfo;
  InputFormat?: string;
  Location?: string;
}
export interface Column {
  Comment?: string;
  Type?: string;
  Name: string;
}
export interface SerdeInfo {
  Parameters?: {
    [k: string]: unknown;
  };
  SerializationLibrary?: string;
  Name?: string;
}
export interface Order {
  Column: string;
  SortOrder: number;
}
export interface SchemaReference {
  SchemaId?: SchemaId;
  SchemaVersionId?: string;
  SchemaVersionNumber?: number;
}
export interface SchemaId {
  RegistryName?: string;
  SchemaName?: string;
  SchemaArn?: string;
}
export interface SkewedInfo {
  SkewedColumnValues?: string[];
  SkewedColumnValueLocationMaps?: {
    [k: string]: unknown;
  };
  SkewedColumnNames?: string[];
}
export interface TableIdentifier {
  DatabaseName?: string;
  CatalogId?: string;
  Name?: string;
}
