/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Evidently::Launch.
 */
export interface AwsEvidentlyLaunch {
  Arn?: string;
  Name: string;
  Project: string;
  Description?: string;
  RandomizationSalt?: string;
  /**
   * @minItems 1
   * @maxItems 6
   */
  ScheduledSplitsConfig:
    | [StepConfig]
    | [StepConfig, StepConfig]
    | [StepConfig, StepConfig, StepConfig]
    | [StepConfig, StepConfig, StepConfig, StepConfig]
    | [StepConfig, StepConfig, StepConfig, StepConfig, StepConfig]
    | [StepConfig, StepConfig, StepConfig, StepConfig, StepConfig, StepConfig];
  /**
   * @minItems 1
   * @maxItems 5
   */
  Groups:
    | [LaunchGroupObject]
    | [LaunchGroupObject, LaunchGroupObject]
    | [LaunchGroupObject, LaunchGroupObject, LaunchGroupObject]
    | [LaunchGroupObject, LaunchGroupObject, LaunchGroupObject, LaunchGroupObject]
    | [LaunchGroupObject, LaunchGroupObject, LaunchGroupObject, LaunchGroupObject, LaunchGroupObject];
  /**
   * @minItems 0
   * @maxItems 3
   */
  MetricMonitors?:
    | []
    | [MetricDefinitionObject]
    | [MetricDefinitionObject, MetricDefinitionObject]
    | [MetricDefinitionObject, MetricDefinitionObject, MetricDefinitionObject];
  /**
   * An array of key-value pairs to apply to this resource.
   */
  Tags?: Tag[];
  ExecutionStatus?: ExecutionStatusObject;
}
export interface StepConfig {
  StartTime: string;
  GroupWeights: GroupToWeight[];
  SegmentOverrides?: SegmentOverride[];
}
export interface GroupToWeight {
  GroupName: string;
  SplitWeight: number;
}
export interface SegmentOverride {
  Segment: string;
  EvaluationOrder: number;
  Weights: GroupToWeight[];
}
export interface LaunchGroupObject {
  GroupName: string;
  Description?: string;
  Feature: string;
  Variation: string;
}
export interface MetricDefinitionObject {
  MetricName: string;
  /**
   * The JSON path to reference the entity id in the event.
   */
  EntityIdKey: string;
  /**
   * The JSON path to reference the numerical metric value in the event.
   */
  ValueKey: string;
  /**
   * Event patterns have the same structure as the events they match. Rules use event patterns to select events. An event pattern either matches an event or it doesn't.
   */
  EventPattern?: string;
  UnitLabel?: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
/**
 * Start or Stop Launch Launch. Default is not started.
 */
export interface ExecutionStatusObject {
  /**
   * Provide START or STOP action to apply on a launch
   */
  Status: string;
  /**
   * Provide CANCELLED or COMPLETED as the launch desired state. Defaults to Completed if not provided.
   */
  DesiredState?: string;
  /**
   * Provide a reason for stopping the launch. Defaults to empty if not provided.
   */
  Reason?: string;
}
