/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Amazon Resource Name of the scheduled query that is generated upon creation.
 */
export type Arn = string;
/**
 * The name of the scheduled query. Scheduled query names must be unique within each Region.
 */
export type ScheduledQueryName = string;
/**
 * The query string to run. Parameter names can be specified in the query string @ character followed by an identifier. The named Parameter @scheduled_runtime is reserved and can be used in the query to get the time at which the query is scheduled to run. The timestamp calculated according to the ScheduleConfiguration parameter, will be the value of @scheduled_runtime paramater for each query run. For example, consider an instance of a scheduled query executing on 2021-12-01 00:00:00. For this instance, the @scheduled_runtime parameter is initialized to the timestamp 2021-12-01 00:00:00 when invoking the query.
 */
export type QueryString = string;
/**
 * An expression that denotes when to trigger the scheduled query run. This can be a cron expression or a rate expression.
 */
export type ScheduleExpression = string;
/**
 * SNS topic ARN that the scheduled query status notifications will be sent to.
 */
export type TopicArn = string;
/**
 * Using a ClientToken makes the call to CreateScheduledQuery idempotent, in other words, making the same request repeatedly will produce the same result. Making multiple identical CreateScheduledQuery requests has the same effect as making a single request. If CreateScheduledQuery is called without a ClientToken, the Query SDK generates a ClientToken on your behalf. After 8 hours, any request with the same ClientToken is treated as a new request.
 */
export type ClientToken = string;
/**
 * The ARN for the IAM role that Timestream will assume when running the scheduled query.
 */
export type ScheduledQueryExecutionRoleArn = string;
/**
 * Name of Timestream database to which the query result will be written.
 */
export type DatabaseName = string;
/**
 * Name of Timestream table that the query result will be written to. The table should be within the same database that is provided in Timestream configuration.
 */
export type TableName = string;
/**
 * Column from query result that should be used as the time column in destination table. Column type for this should be TIMESTAMP.
 */
export type TimeColumn = string;
/**
 * Column name from query result.
 */
export type DimensionMappingName = string;
/**
 * Type for the dimension.
 */
export type DimensionValueType = "VARCHAR";
/**
 * This is to allow mapping column(s) from the query result to the dimension in the destination table.
 */
export type DimensionMappings = DimensionMapping[];
/**
 * Name of the target multi-measure in the derived table. Required if MeasureNameColumn is not provided. If MeasureNameColumn is provided then the value from that column will be used as the multi-measure name.
 */
export type TargetMultiMeasureName = string;
/**
 * Required. Attribute mappings to be used for mapping query results to ingest data for multi-measure attributes.
 *
 * @minItems 1
 */
export type MultiMeasureAttributeMappingList = [MultiMeasureAttributeMapping, ...MultiMeasureAttributeMapping[]];
/**
 * Source measure value column in the query result where the attribute value is to be read.
 */
export type MultiMeasureAttributeMappingSourceColumn = string;
/**
 * Value type of the measure value column to be read from the query result.
 */
export type MultiMeasureAttributeMappingMeasureValueType = "BIGINT" | "BOOLEAN" | "DOUBLE" | "VARCHAR" | "TIMESTAMP";
/**
 * Custom name to be used for attribute name in derived table. If not provided, source column name would be used.
 */
export type TargetMultiMeasureAttributeName = string;
/**
 * Specifies how to map measures to multi-measure records.
 *
 * @minItems 1
 */
export type MixedMeasureMappings = [MixedMeasureMapping, ...MixedMeasureMapping[]];
/**
 * Refers to the value of the measure name in a result row. This field is required if MeasureNameColumn is provided.
 */
export type MixedMeasureMappingMeasureName = string;
/**
 * This field refers to the source column from which the measure value is to be read for result materialization.
 */
export type MixedMeasureMappingSourceColumn = string;
/**
 * Target measure name to be used. If not provided, the target measure name by default would be MeasureName if provided, or SourceColumn otherwise.
 */
export type MixedMeasureMappingTargetMeasureName = string;
/**
 * Type of the value that is to be read from SourceColumn. If the mapping is for MULTI, use MeasureValueType.MULTI.
 */
export type MixedMeasureMappingMeasureValueType = "BIGINT" | "BOOLEAN" | "DOUBLE" | "VARCHAR" | "MULTI";
/**
 * Name of the measure name column from the query result.
 */
export type MeasureNameColumn = string;
/**
 * Name of the S3 bucket under which error reports will be created.
 */
export type BucketName = string;
/**
 * Prefix for error report keys.
 */
export type ObjectKeyPrefix = string;
/**
 * Encryption at rest options for the error reports. If no encryption option is specified, Timestream will choose SSE_S3 as default.
 */
export type EncryptionOption = "SSE_S3" | "SSE_KMS";
/**
 * The Amazon KMS key used to encrypt the scheduled query resource, at-rest. If the Amazon KMS key is not specified, the scheduled query resource will be encrypted with a Timestream owned Amazon KMS key. To specify a KMS key, use the key ID, key ARN, alias name, or alias ARN. When using an alias name, prefix the name with alias/. If ErrorReportConfiguration uses SSE_KMS as encryption type, the same KmsKeyId is used to encrypt the error report at rest.
 */
export type KmsKeyId = string;
/**
 * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
 */
export type Key = string;
/**
 * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
 */
export type Value = string;
/**
 * A list of key-value pairs to label the scheduled query.
 *
 * @maxItems 200
 */
export type Tags = Tag[];

/**
 * The AWS::Timestream::ScheduledQuery resource creates a Timestream Scheduled Query.
 */
export interface AwsTimestreamScheduledquery {
  Arn?: Arn;
  ScheduledQueryName?: ScheduledQueryName;
  QueryString: QueryString;
  ScheduleConfiguration: ScheduleConfiguration;
  NotificationConfiguration: NotificationConfiguration;
  ClientToken?: ClientToken;
  ScheduledQueryExecutionRoleArn: ScheduledQueryExecutionRoleArn;
  TargetConfiguration?: TargetConfiguration;
  ErrorReportConfiguration: ErrorReportConfiguration;
  KmsKeyId?: KmsKeyId;
  /**
   * The name of the scheduled query. Scheduled query names must be unique within each Region.
   */
  SQName?: string;
  /**
   * The query string to run. Parameter names can be specified in the query string @ character followed by an identifier. The named Parameter @scheduled_runtime is reserved and can be used in the query to get the time at which the query is scheduled to run. The timestamp calculated according to the ScheduleConfiguration parameter, will be the value of @scheduled_runtime paramater for each query run. For example, consider an instance of a scheduled query executing on 2021-12-01 00:00:00. For this instance, the @scheduled_runtime parameter is initialized to the timestamp 2021-12-01 00:00:00 when invoking the query.
   */
  SQQueryString?: string;
  /**
   * Configuration for when the scheduled query is executed.
   */
  SQScheduleConfiguration?: string;
  /**
   * Notification configuration for the scheduled query. A notification is sent by Timestream when a query run finishes, when the state is updated or when you delete it.
   */
  SQNotificationConfiguration?: string;
  /**
   * The ARN for the IAM role that Timestream will assume when running the scheduled query.
   */
  SQScheduledQueryExecutionRoleArn?: string;
  /**
   * Configuration of target store where scheduled query results are written to.
   */
  SQTargetConfiguration?: string;
  /**
   * Configuration for error reporting. Error reports will be generated when a problem is encountered when writing the query results.
   */
  SQErrorReportConfiguration?: string;
  /**
   * The Amazon KMS key used to encrypt the scheduled query resource, at-rest. If the Amazon KMS key is not specified, the scheduled query resource will be encrypted with a Timestream owned Amazon KMS key. To specify a KMS key, use the key ID, key ARN, alias name, or alias ARN. When using an alias name, prefix the name with alias/. If ErrorReportConfiguration uses SSE_KMS as encryption type, the same KmsKeyId is used to encrypt the error report at rest.
   */
  SQKmsKeyId?: string;
  Tags?: Tags;
}
/**
 * Configuration for when the scheduled query is executed.
 */
export interface ScheduleConfiguration {
  ScheduleExpression: ScheduleExpression;
}
/**
 * Notification configuration for the scheduled query. A notification is sent by Timestream when a query run finishes, when the state is updated or when you delete it.
 */
export interface NotificationConfiguration {
  SnsConfiguration: SnsConfiguration;
}
/**
 * SNS configuration for notification upon scheduled query execution.
 */
export interface SnsConfiguration {
  TopicArn: TopicArn;
}
/**
 * Configuration of target store where scheduled query results are written to.
 */
export interface TargetConfiguration {
  TimestreamConfiguration: TimestreamConfiguration;
}
/**
 * Configuration needed to write data into the Timestream database and table.
 */
export interface TimestreamConfiguration {
  DatabaseName: DatabaseName;
  TableName: TableName;
  TimeColumn: TimeColumn;
  DimensionMappings: DimensionMappings;
  MultiMeasureMappings?: MultiMeasureMappings;
  MixedMeasureMappings?: MixedMeasureMappings;
  MeasureNameColumn?: MeasureNameColumn;
}
/**
 * This type is used to map column(s) from the query result to a dimension in the destination table.
 */
export interface DimensionMapping {
  Name: DimensionMappingName;
  DimensionValueType: DimensionValueType;
}
/**
 * Only one of MixedMeasureMappings or MultiMeasureMappings is to be provided. MultiMeasureMappings can be used to ingest data as multi measures in the derived table.
 */
export interface MultiMeasureMappings {
  TargetMultiMeasureName?: TargetMultiMeasureName;
  MultiMeasureAttributeMappings: MultiMeasureAttributeMappingList;
}
/**
 * An attribute mapping to be used for mapping query results to ingest data for multi-measure attributes.
 */
export interface MultiMeasureAttributeMapping {
  SourceColumn: MultiMeasureAttributeMappingSourceColumn;
  MeasureValueType: MultiMeasureAttributeMappingMeasureValueType;
  TargetMultiMeasureAttributeName?: TargetMultiMeasureAttributeName;
}
/**
 * MixedMeasureMappings are mappings that can be used to ingest data into a mixture of narrow and multi measures in the derived table.
 */
export interface MixedMeasureMapping {
  MeasureName?: MixedMeasureMappingMeasureName;
  SourceColumn?: MixedMeasureMappingSourceColumn;
  TargetMeasureName?: MixedMeasureMappingTargetMeasureName;
  MeasureValueType: MixedMeasureMappingMeasureValueType;
  MultiMeasureAttributeMappings?: MultiMeasureAttributeMappingList;
}
/**
 * Configuration for error reporting. Error reports will be generated when a problem is encountered when writing the query results.
 */
export interface ErrorReportConfiguration {
  S3Configuration: S3Configuration;
}
/**
 * Details on S3 location for error reports that result from running a query.
 */
export interface S3Configuration {
  BucketName: BucketName;
  ObjectKeyPrefix?: ObjectKeyPrefix;
  EncryptionOption?: EncryptionOption;
}
/**
 * A key-value pair to label the scheduled query.
 */
export interface Tag {
  Key: Key;
  Value: Value;
}
