/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource used to control (enable/disable) DNSSEC in a specific hosted zone.
 */
export interface AwsRoute53Dnssec {
  /**
   * The unique string (ID) used to identify a hosted zone.
   */
  HostedZoneId: string;
}
