/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * You can use AWS::Organizations::ResourcePolicy to delegate policy management for AWS Organizations to specified member accounts to perform policy actions that are by default available only to the management account.
 */
export interface AwsOrganizationsResourcepolicy {
  /**
   * The unique identifier (ID) associated with this resource policy.
   */
  Id?: string;
  /**
   * The Amazon Resource Name (ARN) of the resource policy.
   */
  Arn?: string;
  /**
   * The policy document. For AWS CloudFormation templates formatted in YAML, you can provide the policy in JSON or YAML format. AWS CloudFormation always converts a YAML policy to JSON format before submitting it.
   */
  Content:
    | {
        [k: string]: unknown;
      }
    | string;
  /**
   * A list of tags that you want to attach to the resource policy
   */
  Tags?: Tag[];
}
/**
 * A custom key-value pair associated with a resource within your organization.
 */
export interface Tag {
  /**
   * The key identifier, or name, of the tag.
   */
  Key: string;
  /**
   * The string value that's associated with the key of the tag. You can set the value of a tag to an empty string, but you can't set the value of a tag to null.
   */
  Value: string;
}
