/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Permission set on private certificate authority
 */
export interface AwsAcmpcaPermission {
  /**
   * The actions that the specified AWS service principal can use. Actions IssueCertificate, GetCertificate and ListPermissions must be provided.
   */
  Actions: string[];
  /**
   * The Amazon Resource Name (ARN) of the Private Certificate Authority that grants the permission.
   */
  CertificateAuthorityArn: string;
  /**
   * The AWS service or identity that receives the permission. At this time, the only valid principal is acm.amazonaws.com.
   */
  Principal: string;
  /**
   * The ID of the calling account.
   */
  SourceAccount?: string;
}
