/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Connect::ContactFlow
 */
export interface AwsConnectContactflow {
  /**
   * The identifier of the Amazon Connect instance (ARN).
   */
  InstanceArn: string;
  /**
   * The identifier of the contact flow (ARN).
   */
  ContactFlowArn?: string;
  /**
   * The name of the contact flow.
   */
  Name: string;
  /**
   * The content of the contact flow in JSON format.
   */
  Content: string;
  /**
   * The description of the contact flow.
   */
  Description?: string;
  /**
   * The state of the contact flow.
   */
  State?: "ACTIVE" | "ARCHIVED";
  /**
   * The type of the contact flow.
   */
  Type:
    | "CONTACT_FLOW"
    | "CUSTOMER_QUEUE"
    | "CUSTOMER_HOLD"
    | "CUSTOMER_WHISPER"
    | "AGENT_HOLD"
    | "AGENT_WHISPER"
    | "OUTBOUND_WHISPER"
    | "AGENT_TRANSFER"
    | "QUEUE_TRANSFER";
  /**
   * One or more tags.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. . You can specify a value that is maximum of 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
