/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Mandatory element which enables inbound calls on new instance.
 */
export type InboundCalls = boolean;
/**
 * Mandatory element which enables outbound calls on new instance.
 */
export type OutboundCalls = boolean;
/**
 * Boolean flag which enables CONTACTFLOW_LOGS on an instance.
 */
export type ContactflowLogs = boolean;
/**
 * Boolean flag which enables CONTACT_LENS on an instance.
 */
export type ContactLens = boolean;
/**
 * Boolean flag which enables AUTO_RESOLVE_BEST_VOICES on an instance.
 */
export type AutoResolveBestVoices = boolean;
/**
 * Boolean flag which enables USE_CUSTOM_TTS_VOICES on an instance.
 */
export type UseCustomTTSVoices = boolean;
/**
 * Boolean flag which enables EARLY_MEDIA on an instance.
 */
export type EarlyMedia = boolean;

/**
 * Resource Type definition for AWS::Connect::Instance
 */
export interface AwsConnectInstance {
  /**
   * An instanceId is automatically generated on creation and assigned as the unique identifier.
   */
  Id?: string;
  /**
   * An instanceArn is automatically generated on creation based on instanceId.
   */
  Arn?: string;
  /**
   * Specifies the type of directory integration for new instance.
   */
  IdentityManagementType: "SAML" | "CONNECT_MANAGED" | "EXISTING_DIRECTORY";
  /**
   * Alias of the new directory created as part of new instance creation.
   */
  InstanceAlias?: string;
  /**
   * Timestamp of instance creation logged as part of instance creation.
   */
  CreatedTime?: string;
  /**
   * Service linked role created as part of instance creation.
   */
  ServiceRole?: string;
  /**
   * Specifies the creation status of new instance.
   */
  InstanceStatus?: "CREATION_IN_PROGRESS" | "CREATION_FAILED" | "ACTIVE";
  /**
   * Existing directoryId user wants to map to the new Connect instance.
   */
  DirectoryId?: string;
  Attributes: Attributes;
}
/**
 * The attributes for the instance.
 */
export interface Attributes {
  InboundCalls: InboundCalls;
  OutboundCalls: OutboundCalls;
  ContactflowLogs?: ContactflowLogs;
  ContactLens?: ContactLens;
  AutoResolveBestVoices?: AutoResolveBestVoices;
  UseCustomTTSVoices?: UseCustomTTSVoices;
  EarlyMedia?: EarlyMedia;
}
