/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The list of the task template's invisible fields
 *
 * @maxItems 50
 */
export type InvisibleTaskTemplateFields = InvisibleFieldInfo[];
/**
 * The list of the task template's required fields
 *
 * @maxItems 50
 */
export type RequiredTaskTemplateFields = RequiredFieldInfo[];
/**
 * The list of the task template's read only fields
 *
 * @maxItems 50
 */
export type ReadOnlyTaskTemplateFields = ReadOnlyFieldInfo[];
/**
 * the default value for the task template's field
 */
export type FieldValue = string;
/**
 * The type of the task template's field
 */
export type FieldType =
  | "NAME"
  | "DESCRIPTION"
  | "SCHEDULED_TIME"
  | "QUICK_CONNECT"
  | "URL"
  | "NUMBER"
  | "TEXT"
  | "TEXT_AREA"
  | "DATE_TIME"
  | "BOOLEAN"
  | "SINGLE_SELECT"
  | "EMAIL";
/**
 * Single select field identifier
 */
export type FieldOption = string;
/**
 * The status of the task template
 */
export type Status = "ACTIVE" | "INACTIVE";
/**
 * the client token string in uuid format
 */
export type ClientToken = string;

/**
 * Resource Type definition for AWS::Connect::TaskTemplate.
 */
export interface AwsConnectTasktemplate {
  /**
   * The identifier (arn) of the task template.
   */
  Arn?: string;
  /**
   * The identifier (arn) of the instance.
   */
  InstanceArn: string;
  /**
   * The name of the task template.
   */
  Name?: string;
  /**
   * The description of the task template.
   */
  Description?: string;
  /**
   * The identifier of the contact flow.
   */
  ContactFlowArn?: string;
  /**
   * The constraints for the task template
   */
  Constraints?: {
    InvisibleFields?: InvisibleTaskTemplateFields;
    RequiredFields?: RequiredTaskTemplateFields;
    ReadOnlyFields?: ReadOnlyTaskTemplateFields;
  };
  /**
   * @maxItems 50
   */
  Defaults?: DefaultFieldValue[];
  /**
   * The list of task template's fields
   *
   * @maxItems 50
   */
  Fields?: Field[];
  Status?: Status;
  ClientToken?: ClientToken;
  /**
   * One or more tags.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
}
/**
 * Invisible field info
 */
export interface InvisibleFieldInfo {
  Id: FieldIdentifier;
}
/**
 * the identifier (name) for the task template field
 */
export interface FieldIdentifier {
  /**
   * The name of the task template field
   */
  Name: string;
}
/**
 * Required field info
 */
export interface RequiredFieldInfo {
  Id: FieldIdentifier;
}
/**
 * ReadOnly field info
 */
export interface ReadOnlyFieldInfo {
  Id: FieldIdentifier;
}
/**
 * the default value for the task template's field
 */
export interface DefaultFieldValue {
  Id: FieldIdentifier;
  DefaultValue: FieldValue;
}
/**
 * A task template field object.
 */
export interface Field {
  Id: FieldIdentifier;
  /**
   * The description of the task template's field
   */
  Description?: string;
  Type: FieldType;
  /**
   * list of field options to be used with single select
   *
   * @maxItems 50
   */
  SingleSelectOptions?: FieldOption[];
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. . You can specify a value that is maximum of 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
