/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Connect::UserHierarchyGroup
 */
export interface AwsConnectUserhierarchygroup {
  /**
   * The identifier of the Amazon Connect instance.
   */
  InstanceArn: string;
  /**
   * The Amazon Resource Name (ARN) for the user hierarchy group.
   */
  UserHierarchyGroupArn?: string;
  /**
   * The Amazon Resource Name (ARN) for the parent user hierarchy group.
   */
  ParentGroupArn?: string;
  /**
   * The name of the user hierarchy group.
   */
  Name: string;
}
