/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type Definition for AWS:IdentityStore::GroupMembership
 */
export interface AwsIdentitystoreGroupmembership {
  /**
   * The unique identifier for a group in the identity store.
   */
  GroupId: string;
  /**
   * The globally unique identifier for the identity store.
   */
  IdentityStoreId: string;
  MemberId: UserId;
  /**
   * The identifier for a GroupMembership in the identity store.
   */
  MembershipId?: string;
}
/**
 * An object containing the identifier of a group member.
 */
export interface UserId {
  /**
   * The identifier for a user in the identity store.
   */
  UserId: string;
}
