/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::IoTEvents::Input resource creates an input. To monitor your devices and processes, they must have a way to get telemetry data into AWS IoT Events. This is done by sending messages as *inputs* to AWS IoT Events. For more information, see [How to Use AWS IoT Events](https://docs.aws.amazon.com/iotevents/latest/developerguide/how-to-use-iotevents.html) in the *AWS IoT Events Developer Guide*.
 */
export interface AwsIoteventsInput {
  InputDefinition: InputDefinition;
  /**
   * A brief description of the input.
   */
  InputDescription?: string;
  /**
   * The name of the input.
   */
  InputName?: string;
  /**
   * An array of key-value pairs to apply to this resource.
   *
   * For more information, see [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html).
   */
  Tags?: Tag[];
}
/**
 * The definition of the input.
 */
export interface InputDefinition {
  /**
   * The attributes from the JSON payload that are made available by the input. Inputs are derived from messages sent to the AWS IoT Events system using `BatchPutMessage`. Each such message contains a JSON payload, and those attributes (and their paired values) specified here are available for use in the `condition` expressions used by detectors that monitor this input.
   *
   * @minItems 1
   * @maxItems 200
   */
  Attributes: [Attribute, ...Attribute[]];
}
/**
 * The attributes from the JSON payload that are made available by the input. Inputs are derived from messages sent to the AWS IoT Events system using `BatchPutMessage`. Each such message contains a JSON payload, and those attributes (and their paired values) specified here are available for use in the `condition` expressions used by detectors that monitor this input.
 */
export interface Attribute {
  /**
   * An expression that specifies an attribute-value pair in a JSON structure. Use this to specify an attribute from the JSON payload that is made available by the input. Inputs are derived from messages sent to AWS IoT Events (`BatchPutMessage`). Each such message contains a JSON payload. The attribute (and its paired value) specified here are available for use in the `condition` expressions used by detectors.
   *
   * _Syntax_: `<field-name>.<field-name>...`
   */
  JsonPath: string;
}
/**
 * Tags to be applied to Input.
 */
export interface Tag {
  /**
   * Key of the Tag.
   */
  Key: string;
  /**
   * Value of the Tag.
   */
  Value: string;
}
