/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::MediaLive::Input
 */
export interface AwsMedialiveInput {
  Type?: string;
  Destinations?: InputDestinationRequest[];
  Vpc?: InputVpcRequest;
  MediaConnectFlows?: MediaConnectFlowRequest[];
  Id?: string;
  Arn?: string;
  InputSecurityGroups?: string[];
  Sources?: InputSourceRequest[];
  InputDevices?: InputDeviceSettings[];
  RoleArn?: string;
  Tags?: {
    [k: string]: unknown;
  };
  Name?: string;
}
export interface InputDestinationRequest {
  StreamName?: string;
}
export interface InputVpcRequest {
  SecurityGroupIds?: string[];
  SubnetIds?: string[];
}
export interface MediaConnectFlowRequest {
  FlowArn?: string;
}
export interface InputSourceRequest {
  PasswordParam?: string;
  Username?: string;
  Url?: string;
}
export interface InputDeviceSettings {
  Id?: string;
}
