/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::OpsWorks::App
 */
export interface AwsOpsworksApp {
  Id?: string;
  AppSource?: Source;
  Attributes?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  DataSources?: DataSource[];
  Description?: string;
  Domains?: string[];
  EnableSsl?: boolean;
  Environment?: EnvironmentVariable[];
  Name: string;
  Shortname?: string;
  SslConfiguration?: SslConfiguration;
  StackId: string;
  Type: string;
}
export interface Source {
  Password?: string;
  Revision?: string;
  SshKey?: string;
  Type?: string;
  Url?: string;
  Username?: string;
}
export interface DataSource {
  Arn?: string;
  DatabaseName?: string;
  Type?: string;
}
export interface EnvironmentVariable {
  Key: string;
  Secure?: boolean;
  Value: string;
}
export interface SslConfiguration {
  Certificate?: string;
  Chain?: string;
  PrivateKey?: string;
}
