/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::OpsWorks::Instance
 */
export interface AwsOpsworksInstance {
  Id?: string;
  AvailabilityZone?: string;
  PrivateDnsName?: string;
  PrivateIp?: string;
  PublicDnsName?: string;
  PublicIp?: string;
  AgentVersion?: string;
  AmiId?: string;
  Architecture?: string;
  AutoScalingType?: string;
  BlockDeviceMappings?: BlockDeviceMapping[];
  EbsOptimized?: boolean;
  ElasticIps?: string[];
  Hostname?: string;
  InstallUpdatesOnBoot?: boolean;
  InstanceType: string;
  LayerIds: string[];
  Os?: string;
  RootDeviceType?: string;
  SshKeyName?: string;
  StackId: string;
  SubnetId?: string;
  Tenancy?: string;
  TimeBasedAutoScaling?: TimeBasedAutoScaling;
  VirtualizationType?: string;
  Volumes?: string[];
}
export interface BlockDeviceMapping {
  DeviceName?: string;
  Ebs?: EbsBlockDevice;
  NoDevice?: string;
  VirtualName?: string;
}
export interface EbsBlockDevice {
  DeleteOnTermination?: boolean;
  Iops?: number;
  SnapshotId?: string;
  VolumeSize?: number;
  VolumeType?: string;
}
export interface TimeBasedAutoScaling {
  Friday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  Monday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  Saturday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  Sunday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  Thursday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  Tuesday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  Wednesday?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
}
