/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Key part of key-value pair with value being parameter value
 */
export type ParameterName = string;
/**
 * Value part of key-value pair with key being parameter Name
 */
export type ParameterValue = string;

/**
 * A conformance pack is a collection of AWS Config rules and remediation actions that can be easily deployed as a single entity in an account and a region or across an entire AWS Organization.
 */
export interface AwsConfigConformancepack {
  /**
   * Name of the conformance pack which will be assigned as the unique identifier.
   */
  ConformancePackName: string;
  /**
   * AWS Config stores intermediate files while processing conformance pack template.
   */
  DeliveryS3Bucket?: string;
  /**
   * The prefix for delivery S3 bucket.
   */
  DeliveryS3KeyPrefix?: string;
  /**
   * A string containing full conformance pack template body. You can only specify one of the template body or template S3Uri fields.
   */
  TemplateBody?: string;
  /**
   * Location of file containing the template body which points to the conformance pack template that is located in an Amazon S3 bucket. You can only specify one of the template body or template S3Uri fields.
   */
  TemplateS3Uri?: string;
  /**
   * The TemplateSSMDocumentDetails object contains the name of the SSM document and the version of the SSM document.
   */
  TemplateSSMDocumentDetails?: {
    DocumentName?: string;
    DocumentVersion?: string;
  };
  /**
   * A list of ConformancePackInputParameter objects.
   *
   * @minItems 0
   * @maxItems 60
   */
  ConformancePackInputParameters?: ConformancePackInputParameter[];
}
/**
 * Input parameters in the form of key-value pairs for the conformance pack.
 */
export interface ConformancePackInputParameter {
  ParameterName: ParameterName;
  ParameterValue: ParameterValue;
}
