/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ParameterName = string;
export type ParameterValue = string;
export type AccountId = string;

/**
 * Resource schema for AWS::Config::OrganizationConformancePack.
 */
export interface AwsConfigOrganizationconformancepack {
  /**
   * The name of the organization conformance pack.
   */
  OrganizationConformancePackName: string;
  /**
   * Location of file containing the template body.
   */
  TemplateS3Uri?: string;
  /**
   * A string containing full conformance pack template body.
   */
  TemplateBody?: string;
  /**
   * AWS Config stores intermediate files while processing conformance pack template.
   */
  DeliveryS3Bucket?: string;
  /**
   * The prefix for the delivery S3 bucket.
   */
  DeliveryS3KeyPrefix?: string;
  /**
   * A list of ConformancePackInputParameter objects.
   *
   * @minItems 0
   * @maxItems 60
   */
  ConformancePackInputParameters?: ConformancePackInputParameter[];
  /**
   * A list of AWS accounts to be excluded from an organization conformance pack while deploying a conformance pack.
   *
   * @minItems 0
   * @maxItems 1000
   */
  ExcludedAccounts?: AccountId[];
}
/**
 * Input parameters in the form of key-value pairs for the conformance pack.
 */
export interface ConformancePackInputParameter {
  ParameterName: ParameterName;
  ParameterValue: ParameterValue;
  [k: string]: unknown;
}
