/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FrequencyUnits = "GHz" | "MHz" | "kHz";
export type BandwidthUnits = "GHz" | "MHz" | "kHz";
export type Polarization = "LEFT_HAND" | "RIGHT_HAND" | "NONE";
export type JsonString = string;
export type EirpUnits = "dBW";
export type BucketArn = string;
export type RoleArn = string;
export type S3KeyPrefix = string;

/**
 * AWS Ground Station config resource type for CloudFormation.
 */
export interface AwsGroundstationConfig {
  Name: string;
  Tags?: Tag[];
  Type?: string;
  ConfigData: ConfigData;
  Arn?: string;
  Id?: string;
}
export interface Tag {
  Key?: string;
  Value?: string;
}
export interface ConfigData {
  AntennaDownlinkConfig?: AntennaDownlinkConfig;
  TrackingConfig?: TrackingConfig;
  DataflowEndpointConfig?: DataflowEndpointConfig;
  AntennaDownlinkDemodDecodeConfig?: AntennaDownlinkDemodDecodeConfig;
  AntennaUplinkConfig?: AntennaUplinkConfig;
  UplinkEchoConfig?: UplinkEchoConfig;
  S3RecordingConfig?: S3RecordingConfig;
}
export interface AntennaDownlinkConfig {
  SpectrumConfig?: SpectrumConfig;
}
export interface SpectrumConfig {
  CenterFrequency?: Frequency;
  Bandwidth?: FrequencyBandwidth;
  Polarization?: Polarization;
}
export interface Frequency {
  Value?: number;
  Units?: FrequencyUnits;
}
export interface FrequencyBandwidth {
  Value?: number;
  Units?: BandwidthUnits;
}
export interface TrackingConfig {
  Autotrack?: "REQUIRED" | "PREFERRED" | "REMOVED";
}
export interface DataflowEndpointConfig {
  DataflowEndpointName?: string;
  DataflowEndpointRegion?: string;
}
export interface AntennaDownlinkDemodDecodeConfig {
  SpectrumConfig?: SpectrumConfig;
  DemodulationConfig?: DemodulationConfig;
  DecodeConfig?: DecodeConfig;
}
export interface DemodulationConfig {
  UnvalidatedJSON?: JsonString;
}
export interface DecodeConfig {
  UnvalidatedJSON?: JsonString;
}
export interface AntennaUplinkConfig {
  SpectrumConfig?: UplinkSpectrumConfig;
  TargetEirp?: Eirp;
  TransmitDisabled?: boolean;
}
export interface UplinkSpectrumConfig {
  CenterFrequency?: Frequency;
  Polarization?: Polarization;
}
export interface Eirp {
  Value?: number;
  Units?: EirpUnits;
}
export interface UplinkEchoConfig {
  Enabled?: boolean;
  AntennaUplinkConfigArn?: string;
}
export interface S3RecordingConfig {
  BucketArn?: BucketArn;
  RoleArn?: RoleArn;
  Prefix?: S3KeyPrefix;
}
