/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::VoiceID::Domain resource specifies an Amazon VoiceID Domain.
 */
export interface AwsVoiceidDomain {
  Description?: string;
  DomainId?: string;
  Name: string;
  ServerSideEncryptionConfiguration: ServerSideEncryptionConfiguration;
  /**
   * @minItems 0
   * @maxItems 200
   */
  Tags?: Tag[];
}
export interface ServerSideEncryptionConfiguration {
  KmsKeyId: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
