/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A pseudo-resource that manages which of your ECS task sets is primary.
 */
export interface AwsEcsPrimarytaskset {
  /**
   * The short name or full Amazon Resource Name (ARN) of the cluster that hosts the service to create the task set in.
   */
  Cluster: string;
  /**
   * The ID or full Amazon Resource Name (ARN) of the task set.
   */
  TaskSetId: string;
  /**
   * The short name or full Amazon Resource Name (ARN) of the service to create the task set in.
   */
  Service: string;
}
