/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `TagMap`'s JSON-Schema definition
 * via the `patternProperty` ".{1,128}".
 */
export type TagValue = string;

/**
 * Resource Type Definition for Resiliency Policy.
 */
export interface AwsResiliencehubResiliencypolicy {
  /**
   * Name of Resiliency Policy.
   */
  PolicyName: string;
  /**
   * Description of Resiliency Policy.
   */
  PolicyDescription?: string;
  /**
   * Data Location Constraint of the Policy.
   */
  DataLocationConstraint?: "AnyLocation" | "SameContinent" | "SameCountry";
  /**
   * Resiliency Policy Tier.
   */
  Tier: "MissionCritical" | "Critical" | "Important" | "CoreServices" | "NonCritical";
  Policy: PolicyMap;
  /**
   * Amazon Resource Name (ARN) of the Resiliency Policy.
   */
  PolicyArn?: string;
  Tags?: TagMap;
}
export interface PolicyMap {
  [k: string]: FailurePolicy;
}
/**
 * Failure Policy.
 *
 * This interface was referenced by `PolicyMap`'s JSON-Schema definition
 * via the `patternProperty` ".*{1,8}".
 */
export interface FailurePolicy {
  /**
   * RTO in seconds.
   */
  RtoInSecs: number;
  /**
   * RPO in seconds.
   */
  RpoInSecs: number;
}
export interface TagMap {
  [k: string]: TagValue;
}
