/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Definition of AWS::Omics::RunGroup Resource Type
 */
export interface AwsOmicsRungroup {
  Arn?: string;
  CreationTime?: string;
  Id?: string;
  MaxCpus?: number;
  MaxDuration?: number;
  MaxRuns?: number;
  Name?: string;
  Tags?: TagMap;
}
/**
 * A map of resource tags
 */
export interface TagMap {
  /**
   * Resource tag value
   *
   * This interface was referenced by `TagMap`'s JSON-Schema definition
   * via the `patternProperty` ".+".
   */
  [k: string]: string;
}
