/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of comma separated tags to add to the data catalog that is created.
 */
export type Tags = Tag[];

/**
 * Resource schema for AWS::Athena::DataCatalog
 */
export interface AwsAthenaDatacatalog {
  /**
   * The name of the data catalog to create. The catalog name must be unique for the AWS account and can use a maximum of 128 alphanumeric, underscore, at sign, or hyphen characters.
   */
  Name: string;
  /**
   * A description of the data catalog to be created.
   */
  Description?: string;
  /**
   * Specifies the Lambda function or functions to use for creating the data catalog. This is a mapping whose values depend on the catalog type.
   */
  Parameters?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".*".
     */
    [k: string]: string;
  };
  Tags?: Tags;
  /**
   * The type of data catalog to create: LAMBDA for a federated catalog, GLUE for AWS Glue Catalog, or HIVE for an external hive metastore.
   */
  Type: "LAMBDA" | "GLUE" | "HIVE";
}
export interface Tag {
  Key: string;
  Value: string;
}
