/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enables a control on a specified target.
 */
export interface AwsControltowerEnabledcontrol {
  /**
   * Arn of the control.
   */
  ControlIdentifier: string;
  /**
   * Arn for Organizational unit to which the control needs to be applied
   */
  TargetIdentifier: string;
}
