/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Transfer::Certificate
 */
export interface AwsTransferCertificate {
  /**
   * Specifies the usage type for the certificate.
   */
  Usage: "SIGNING" | "ENCRYPTION";
  /**
   * Specifies the certificate body to be imported.
   */
  Certificate: string;
  /**
   * Specifies the certificate chain to be imported.
   */
  CertificateChain?: string;
  /**
   * Specifies the private key for the certificate.
   */
  PrivateKey?: string;
  /**
   * Specifies the active date for the certificate.
   */
  ActiveDate?: string;
  /**
   * Specifies the inactive date for the certificate.
   */
  InactiveDate?: string;
  /**
   * A textual description for the certificate.
   */
  Description?: string;
  /**
   * Key-value pairs that can be used to group and search for certificates. Tags are metadata attached to certificates for any purpose.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
  /**
   * Specifies the unique Amazon Resource Name (ARN) for the agreement.
   */
  Arn?: string;
  /**
   * A unique identifier for the certificate.
   */
  CertificateId?: string;
  /**
   * A status description for the certificate.
   */
  Status?: "ACTIVE" | "PENDING" | "INACTIVE";
  /**
   * Describing the type of certificate. With or without a private key.
   */
  Type?: "CERTIFICATE" | "CERTIFICATE_WITH_PRIVATE_KEY";
  /**
   * Specifies Certificate's serial.
   */
  Serial?: string;
  /**
   * Specifies the not before date for the certificate.
   */
  NotBeforeDate?: string;
  /**
   * Specifies the not after date for the certificate.
   */
  NotAfterDate?: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
