/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ARN of the Scheduling Policy.
 */
export type ResourceArn = string;

/**
 * Resource Type schema for AWS::Batch::SchedulingPolicy
 */
export interface AwsBatchSchedulingpolicy {
  /**
   * Name of Scheduling Policy.
   */
  Name?: string;
  Arn?: ResourceArn;
  FairsharePolicy?: FairsharePolicy;
  /**
   * A key-value pair to associate with a resource.
   */
  Tags?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".*".
     */
    [k: string]: string;
  };
}
/**
 * Fair Share Policy for the Job Queue.
 */
export interface FairsharePolicy {
  ShareDecaySeconds?: number;
  ComputeReservation?: number;
  /**
   * List of Share Attributes
   */
  ShareDistribution?: ShareAttributes[];
}
export interface ShareAttributes {
  ShareIdentifier?: string;
  WeightFactor?: number;
}
