/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The possible types for the access policy
 */
export type AccessPolicyType = "data";

/**
 * Amazon OpenSearchServerless access policy resource
 */
export interface AwsOpensearchserverlessAccesspolicy {
  /**
   * The name of the policy
   */
  Name?: string;
  Type?: AccessPolicyType;
  /**
   * The description of the policy
   */
  Description?: string;
  /**
   * The JSON policy document that is the content for the policy
   */
  Policy?: string;
}
