/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SNS::Subscription
 */
export interface AwsSnsSubscription {
  RawMessageDelivery?: boolean;
  Endpoint?: string;
  FilterPolicy?: {
    [k: string]: unknown;
  };
  TopicArn: string;
  RedrivePolicy?: {
    [k: string]: unknown;
  };
  DeliveryPolicy?: {
    [k: string]: unknown;
  };
  Region?: string;
  SubscriptionRoleArn?: string;
  FilterPolicyScope?: string;
  Id?: string;
  Protocol: string;
}
