/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Macie FindingsFilter resource schema.
 */
export interface AwsMacieFindingsfilter {
  /**
   * Findings filter name
   */
  Name: string;
  /**
   * Findings filter description
   */
  Description?: string;
  FindingCriteria: FindingCriteria;
  /**
   * Findings filter action.
   */
  Action?: "ARCHIVE" | "NOOP";
  /**
   * Findings filter position.
   */
  Position?: number;
  /**
   * Findings filter ID.
   */
  Id?: string;
  /**
   * Findings filter ARN.
   */
  Arn?: string;
  /**
   * Findings filters list.
   */
  FindingsFilterListItems?: FindingsFilterListItem[];
}
/**
 * Findings filter criteria.
 */
export interface FindingCriteria {
  Criterion?: Criterion;
  [k: string]: unknown;
}
/**
 * Map of filter criteria.
 */
export interface Criterion {
  [k: string]: CriterionAdditionalProperties;
}
/**
 * This interface was referenced by `Criterion`'s JSON-Schema definition
 * via the `patternProperty` "\w".
 */
export interface CriterionAdditionalProperties {
  gt?: number;
  gte?: number;
  lt?: number;
  lte?: number;
  eq?: string[];
  neq?: string[];
  [k: string]: unknown;
}
/**
 * Returned by ListHandler representing filter name and ID.
 */
export interface FindingsFilterListItem {
  Id?: string;
  Name?: string;
  [k: string]: unknown;
}
