/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A resource schema for a Detector in Amazon Fraud Detector.
 */
export interface AwsFrauddetectorDetector {
  /**
   * The ID of the detector
   */
  DetectorId: string;
  /**
   * The desired detector version status for the detector
   */
  DetectorVersionStatus?: "DRAFT" | "ACTIVE";
  /**
   * The active version ID of the detector
   */
  DetectorVersionId?: string;
  RuleExecutionMode?: "FIRST_MATCHED" | "ALL_MATCHED";
  /**
   * Tags associated with this detector.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The description of the detector.
   */
  Description?: string;
  /**
   * @minItems 1
   */
  Rules: [Rule, ...Rule[]];
  EventType: EventType;
  /**
   * The ARN of the detector.
   */
  Arn?: string;
  /**
   * The time when the detector was created.
   */
  CreatedTime?: string;
  /**
   * The time when the detector was last updated.
   */
  LastUpdatedTime?: string;
  /**
   * The models to associate with this detector.
   *
   * @maxItems 10
   */
  AssociatedModels?:
    | []
    | [Model]
    | [Model, Model]
    | [Model, Model, Model]
    | [Model, Model, Model, Model]
    | [Model, Model, Model, Model, Model]
    | [Model, Model, Model, Model, Model, Model]
    | [Model, Model, Model, Model, Model, Model, Model]
    | [Model, Model, Model, Model, Model, Model, Model, Model]
    | [Model, Model, Model, Model, Model, Model, Model, Model, Model]
    | [Model, Model, Model, Model, Model, Model, Model, Model, Model, Model];
}
export interface Tag {
  Key: string;
  Value: string;
}
export interface Rule {
  RuleId?: string;
  RuleVersion?: string;
  DetectorId?: string;
  Expression?: string;
  Language?: "DETECTORPL";
  /**
   * @minItems 1
   */
  Outcomes?: [Outcome, ...Outcome[]];
  Arn?: string;
  /**
   * The description.
   */
  Description?: string;
  /**
   * Tags associated with this event type.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The time when the event type was created.
   */
  CreatedTime?: string;
  /**
   * The time when the event type was last updated.
   */
  LastUpdatedTime?: string;
}
export interface Outcome {
  Arn?: string;
  Inline?: boolean;
  Name?: string;
  /**
   * The description.
   */
  Description?: string;
  /**
   * Tags associated with this outcome.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The time when the outcome was created.
   */
  CreatedTime?: string;
  /**
   * The time when the outcome was last updated.
   */
  LastUpdatedTime?: string;
}
/**
 * The event type to associate this detector with.
 */
export interface EventType {
  /**
   * The name for the event type
   */
  Name?: string;
  Inline?: boolean;
  /**
   * Tags associated with this event type.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The description of the event type.
   */
  Description?: string;
  /**
   * @minItems 1
   */
  EventVariables?: [EventVariable, ...EventVariable[]];
  /**
   * @minItems 2
   */
  Labels?: [Label, Label, ...Label[]];
  /**
   * @minItems 1
   */
  EntityTypes?: [EntityType, ...EntityType[]];
  /**
   * The ARN of the event type.
   */
  Arn?: string;
  /**
   * The time when the event type was created.
   */
  CreatedTime?: string;
  /**
   * The time when the event type was last updated.
   */
  LastUpdatedTime?: string;
}
export interface EventVariable {
  Arn?: string;
  Inline?: boolean;
  Name?: string;
  DataSource?: "EVENT";
  DataType?: "STRING" | "INTEGER" | "FLOAT" | "BOOLEAN";
  DefaultValue?: string;
  VariableType?:
    | "AUTH_CODE"
    | "AVS"
    | "BILLING_ADDRESS_L1"
    | "BILLING_ADDRESS_L2"
    | "BILLING_CITY"
    | "BILLING_COUNTRY"
    | "BILLING_NAME"
    | "BILLING_PHONE"
    | "BILLING_STATE"
    | "BILLING_ZIP"
    | "CARD_BIN"
    | "CATEGORICAL"
    | "CURRENCY_CODE"
    | "EMAIL_ADDRESS"
    | "FINGERPRINT"
    | "FRAUD_LABEL"
    | "FREE_FORM_TEXT"
    | "IP_ADDRESS"
    | "NUMERIC"
    | "ORDER_ID"
    | "PAYMENT_TYPE"
    | "PHONE_NUMBER"
    | "PRICE"
    | "PRODUCT_CATEGORY"
    | "SHIPPING_ADDRESS_L1"
    | "SHIPPING_ADDRESS_L2"
    | "SHIPPING_CITY"
    | "SHIPPING_COUNTRY"
    | "SHIPPING_NAME"
    | "SHIPPING_PHONE"
    | "SHIPPING_STATE"
    | "SHIPPING_ZIP"
    | "USERAGENT";
  /**
   * The description.
   */
  Description?: string;
  /**
   * Tags associated with this event variable.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The time when the event variable was created.
   */
  CreatedTime?: string;
  /**
   * The time when the event variable was last updated.
   */
  LastUpdatedTime?: string;
}
export interface Label {
  Arn?: string;
  Inline?: boolean;
  Name?: string;
  /**
   * The description.
   */
  Description?: string;
  /**
   * Tags associated with this label.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The time when the label was created.
   */
  CreatedTime?: string;
  /**
   * The time when the label was last updated.
   */
  LastUpdatedTime?: string;
}
export interface EntityType {
  Arn?: string;
  Inline?: boolean;
  Name?: string;
  /**
   * The description.
   */
  Description?: string;
  /**
   * Tags associated with this entity type.
   *
   * @maxItems 200
   */
  Tags?: Tag[];
  /**
   * The time when the entity type was created.
   */
  CreatedTime?: string;
  /**
   * The time when the entity type was last updated.
   */
  LastUpdatedTime?: string;
}
/**
 * A model to associate with a detector.
 */
export interface Model {
  Arn?: string;
}
