/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AppIntegrations::EventIntegration
 */
export interface AwsAppintegrationsEventintegration {
  /**
   * The event integration description.
   */
  Description?: string;
  /**
   * The Amazon Resource Name (ARN) of the event integration.
   */
  EventIntegrationArn?: string;
  /**
   * The name of the event integration.
   */
  Name: string;
  /**
   * The Amazon Eventbridge bus for the event integration.
   */
  EventBridgeBus: string;
  EventFilter: EventFilter;
  /**
   * The tags (keys and values) associated with the event integration.
   *
   * @minItems 0
   * @maxItems 200
   */
  Tags?: Tag[];
}
/**
 * The EventFilter (source) associated with the event integration.
 */
export interface EventFilter {
  /**
   * The source of the events.
   */
  Source: string;
}
export interface Tag {
  /**
   * A key to identify the tag.
   */
  Key: string;
  /**
   * Corresponding tag value for the key.
   */
  Value: string;
}
