/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::PinpointEmail::DedicatedIpPool
 */
export interface AwsPinpointemailDedicatedippool {
  Id?: string;
  PoolName?: string;
  Tags?: Tags[];
}
export interface Tags {
  Value?: string;
  Key?: string;
}
