/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource schema for AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation.
 */
export interface AwsRoute53ResolverResolverqueryloggingconfigassociation {
  /**
   * Id
   */
  Id?: string;
  /**
   * ResolverQueryLogConfigId
   */
  ResolverQueryLogConfigId?: string;
  /**
   * ResourceId
   */
  ResourceId?: string;
  /**
   * ResolverQueryLogConfigAssociationStatus
   */
  Status?: "CREATING" | "ACTIVE" | "ACTION_NEEDED" | "DELETING" | "FAILED" | "OVERRIDDEN";
  /**
   * ResolverQueryLogConfigAssociationError
   */
  Error?: "NONE" | "DESTINATION_NOT_FOUND" | "ACCESS_DENIED";
  /**
   * ResolverQueryLogConfigAssociationErrorMessage
   */
  ErrorMessage?: string;
  /**
   * Rfc3339TimeString
   */
  CreationTime?: string;
}
