/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SageMaker::App
 */
export interface AwsSagemakerApp {
  /**
   * The Amazon Resource Name (ARN) of the app.
   */
  AppArn?: string;
  /**
   * The name of the app.
   */
  AppName: string;
  /**
   * The type of app.
   */
  AppType: "JupyterServer" | "KernelGateway" | "RStudioServerPro" | "RSessionGateway" | "Canvas";
  /**
   * The domain ID.
   */
  DomainId: string;
  ResourceSpec?: ResourceSpec;
  /**
   * A list of tags to apply to the app.
   *
   * @minItems 0
   * @maxItems 50
   */
  Tags?: Tag[];
  /**
   * The user profile name.
   */
  UserProfileName: string;
}
/**
 * The instance type and the Amazon Resource Name (ARN) of the SageMaker image created on the instance.
 */
export interface ResourceSpec {
  /**
   * The instance type that the image version runs on.
   */
  InstanceType?:
    | "system"
    | "ml.t3.micro"
    | "ml.t3.small"
    | "ml.t3.medium"
    | "ml.t3.large"
    | "ml.t3.xlarge"
    | "ml.t3.2xlarge"
    | "ml.m5.large"
    | "ml.m5.xlarge"
    | "ml.m5.2xlarge"
    | "ml.m5.4xlarge"
    | "ml.m5.8xlarge"
    | "ml.m5.12xlarge"
    | "ml.m5.16xlarge"
    | "ml.m5.24xlarge"
    | "ml.c5.large"
    | "ml.c5.xlarge"
    | "ml.c5.2xlarge"
    | "ml.c5.4xlarge"
    | "ml.c5.9xlarge"
    | "ml.c5.12xlarge"
    | "ml.c5.18xlarge"
    | "ml.c5.24xlarge"
    | "ml.p3.2xlarge"
    | "ml.p3.8xlarge"
    | "ml.p3.16xlarge"
    | "ml.g4dn.xlarge"
    | "ml.g4dn.2xlarge"
    | "ml.g4dn.4xlarge"
    | "ml.g4dn.8xlarge"
    | "ml.g4dn.12xlarge"
    | "ml.g4dn.16xlarge"
    | "ml.r5.large"
    | "ml.r5.xlarge"
    | "ml.r5.2xlarge"
    | "ml.r5.4xlarge"
    | "ml.r5.8xlarge"
    | "ml.r5.12xlarge"
    | "ml.r5.16xlarge"
    | "ml.r5.24xlarge"
    | "ml.p3dn.24xlarge"
    | "ml.m5d.large"
    | "ml.m5d.xlarge"
    | "ml.m5d.2xlarge"
    | "ml.m5d.4xlarge"
    | "ml.m5d.8xlarge"
    | "ml.m5d.12xlarge"
    | "ml.m5d.16xlarge"
    | "ml.m5d.24xlarge"
    | "ml.g5.xlarge"
    | "ml.g5.2xlarge"
    | "ml.g5.4xlarge"
    | "ml.g5.8xlarge"
    | "ml.g5.12xlarge"
    | "ml.g5.16xlarge"
    | "ml.g5.24xlarge"
    | "ml.g5.48xlarge";
  /**
   * The ARN of the SageMaker image that the image version belongs to.
   */
  SageMakerImageArn?: string;
  /**
   * The ARN of the image version created on the instance.
   */
  SageMakerImageVersionArn?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
