/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SageMaker::NotebookInstanceLifecycleConfig
 */
export interface AwsSagemakerNotebookinstancelifecycleconfig {
  Id?: string;
  NotebookInstanceLifecycleConfigName?: string;
  OnStart?: NotebookInstanceLifecycleHook[];
  OnCreate?: NotebookInstanceLifecycleHook[];
}
export interface NotebookInstanceLifecycleHook {
  Content?: string;
}
