/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An IPV4 address
 */
export type IpAddress = string;

/**
 * Resource Type definition for AWS::GlobalAccelerator::Accelerator
 */
export interface AwsGlobalacceleratorAccelerator {
  /**
   * Name of accelerator.
   */
  Name: string;
  /**
   * IP Address type.
   */
  IpAddressType?: "IPV4" | "DUAL_STACK";
  /**
   * The IP addresses from BYOIP Prefix pool.
   */
  IpAddresses?: IpAddress[];
  /**
   * Indicates whether an accelerator is enabled. The value is true or false.
   */
  Enabled?: boolean;
  /**
   * The Domain Name System (DNS) name that Global Accelerator creates that points to your accelerator's static IPv4 addresses.
   */
  DnsName?: string;
  /**
   * The IPv4 addresses assigned to the accelerator.
   */
  Ipv4Addresses?: string[];
  /**
   * The IPv6 addresses assigned if the accelerator is dualstack
   */
  Ipv6Addresses?: string[];
  /**
   * The Domain Name System (DNS) name that Global Accelerator creates that points to your accelerator's static IPv4 and IPv6 addresses.
   */
  DualStackDnsName?: string;
  /**
   * The Amazon Resource Name (ARN) of the accelerator.
   */
  AcceleratorArn?: string;
  Tags?: Tag[];
}
/**
 * Tag is a key-value pair associated with accelerator.
 */
export interface Tag {
  /**
   * Key of the tag. Value can be 1 to 127 characters.
   */
  Key: string;
  /**
   * Value for the tag. Value can be 1 to 255 characters.
   */
  Value: string;
}
