/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::MemoryDB::ParameterGroup resource creates an Amazon MemoryDB ParameterGroup.
 */
export interface AwsMemorydbParametergroup {
  /**
   * The name of the parameter group.
   */
  ParameterGroupName: string;
  /**
   * The name of the parameter group family that this parameter group is compatible with.
   */
  Family: string;
  /**
   * A description of the parameter group.
   */
  Description?: string;
  /**
   * An array of key-value pairs to apply to this parameter group.
   *
   * @maxItems 50
   */
  Tags?: Tag[];
  /**
   * An map of parameter names and values for the parameter update. You must supply at least one parameter name and value; subsequent arguments are optional.
   */
  Parameters?: {
    [k: string]: unknown;
  };
  /**
   * The Amazon Resource Name (ARN) of the parameter group.
   */
  ARN?: string;
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key for the tag. May not be null.
   */
  Key: string;
  /**
   * The tag's value. May be null.
   */
  Value: string;
}
