/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ServiceEndpointType = "LAMBDA" | "URL";

/**
 * Definition of AWS::RefactorSpaces::Service Resource Type
 */
export interface AwsRefactorspacesService {
  Arn?: string;
  ApplicationIdentifier: string;
  Description?: string;
  EndpointType?: ServiceEndpointType;
  EnvironmentIdentifier: string;
  LambdaEndpoint?: LambdaEndpointInput;
  Name?: string;
  ServiceIdentifier?: string;
  UrlEndpoint?: UrlEndpointInput;
  VpcId?: string;
  /**
   * Metadata that you can assign to help organize the frameworks that you create. Each tag is a key-value pair.
   */
  Tags?: Tag[];
}
export interface LambdaEndpointInput {
  Arn: string;
}
export interface UrlEndpointInput {
  HealthUrl?: string;
  Url: string;
}
/**
 * A label for tagging Environment resource
 */
export interface Tag {
  /**
   * A string used to identify this tag
   */
  Key: string;
  /**
   * A string containing the value for the tag
   */
  Value: string;
}
