/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A resource ARN.
 */
export type ResourceArn = string;

/**
 * Designates the IAM role and Amazon Simple Notification Service (SNS) topic that AWS Firewall Manager uses to record SNS logs.
 */
export interface AwsFmsNotificationchannel {
  SnsRoleName: ResourceArn;
  SnsTopicArn: ResourceArn;
}
