/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Arn = string;

/**
 * Resource Type definition for AWS::AppStream::ApplicationFleetAssociation
 */
export interface AwsAppstreamApplicationfleetassociation {
  FleetName: string;
  ApplicationArn: Arn;
}
