/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AppStream::ImageBuilder
 */
export interface AwsAppstreamImagebuilder {
  Description?: string;
  VpcConfig?: VpcConfig;
  EnableDefaultInternetAccess?: boolean;
  DomainJoinInfo?: DomainJoinInfo;
  AppstreamAgentVersion?: string;
  Name: string;
  ImageName?: string;
  DisplayName?: string;
  IamRoleArn?: string;
  InstanceType: string;
  Tags?: Tag[];
  StreamingUrl?: string;
  ImageArn?: string;
  AccessEndpoints?: AccessEndpoint[];
}
export interface VpcConfig {
  SecurityGroupIds?: string[];
  SubnetIds?: string[];
}
export interface DomainJoinInfo {
  OrganizationalUnitDistinguishedName?: string;
  DirectoryName?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface AccessEndpoint {
  EndpointType: string;
  VpceId: string;
}
