/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AppStream::User
 */
export interface AwsAppstreamUser {
  Id?: string;
  UserName: string;
  FirstName?: string;
  MessageAction?: string;
  LastName?: string;
  AuthenticationType: string;
}
