/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ApiGateway::UsagePlanKey
 */
export interface AwsApigatewayUsageplankey {
  /**
   * The ID of the usage plan key.
   */
  KeyId: string;
  /**
   * The type of usage plan key. Currently, the only valid key type is API_KEY.
   */
  KeyType: "API_KEY";
  /**
   * The ID of the usage plan.
   */
  UsagePlanId: string;
  /**
   * An autogenerated ID which is a combination of the ID of the key and ID of the usage plan combined with a : such as 123abcdef:abc123.
   */
  Id?: string;
}
