/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ElasticLoadBalancingV2::ListenerCertificate
 */
export interface AwsElasticloadbalancingv2Listenercertificate {
  ListenerArn: string;
  Certificates: Certificate[];
  Id?: string;
}
export interface Certificate {
  CertificateArn?: string;
}
