/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A resource ARN.
 */
export type ResourceArn = string;
/**
 * An endpoint Id.
 */
export type EndpointId = string;

/**
 * Resource type definition for AWS::NetworkFirewall::Firewall
 */
export interface AwsNetworkfirewallFirewall {
  FirewallName: string;
  FirewallArn?: ResourceArn;
  FirewallId?: string;
  FirewallPolicyArn: ResourceArn;
  VpcId: string;
  /**
   * @minItems 1
   */
  SubnetMappings: [SubnetMapping, ...SubnetMapping[]];
  DeleteProtection?: boolean;
  SubnetChangeProtection?: boolean;
  FirewallPolicyChangeProtection?: boolean;
  Description?: string;
  EndpointIds?: EndpointId[];
  Tags?: Tag[];
}
export interface SubnetMapping {
  /**
   * A SubnetId.
   */
  SubnetId: string;
  /**
   * A IPAddressType
   */
  IPAddressType?: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
